// AUTO-GENERATED, one-time verified batch — DO NOT hand-edit casually.
// Static mapping of bc_liquor beer rows (keyed by exact product_name) to the
// curated ALCOHOL_PRODUCTS id they are the SAME national product as. Produced by
// a guarded fuzzy match (brand+name token overlap + variant-keyword guard +
// ABV within ±0.5%); 88 confirmed beer matches. Wine was excluded
// (unreliable without producer-level matching). Unmatched bc rows keep the bare listing.
import { ALCOHOL_PRODUCTS, type AlcoholRankingProduct } from "../alcohol/lib/products";

export const BC_BEER_MATCHES: Record<string, string> = {
  "ASAHI - SUPER DRY": "asahi-super-dry-330ml",
  "ASAHI SUPER DRY": "asahi-super-dry-330ml",
  "ASAHI SUPER DRY BIG CAN": "asahi-super-dry-330ml",
  "BALDERDASH BREWING - SNEAKY WEASEL CRAFT LAGER": "sneaky-weasel-473ml",
  "BALDERDASH BREWING - SNEAKY WEASEL CRAFT LAGER CAN": "sneaky-weasel-473ml",
  "BALDERDASH BREWING - SNEAKY WEASEL CRAFT LAGER TALL CAN": "sneaky-weasel-473ml",
  "BIRRA MORETTI": "birra-moretti-birra-moretti",
  "BLUE MOON - MANGO WHEAT TALL CAN": "blue-moon-mango-wheat-473ml",
  "BLUE MOON - WHITE CAN": "blue-moon-belgian-white-473ml",
  "BLUE MOON - WHITE TALL CAN": "blue-moon-belgian-white-473ml",
  "CARLSBERG - PILSNER TALL CAN": "carlsberg-pilsner-473ml",
  "COLUMBIA - KOKANEE": "kokanee-355ml",
  "COLUMBIA - KOKANEE CAN": "kokanee-355ml",
  "COORS LIGHT - CAN": "coors-light",
  "COORS LIGHT - TALL CAN": "coors-light",
  "CORONA LIGHT 6 BOTTLE": "corona-light",
  "DOS EQUIS - LAGER": "dos-equis-lager",
  "DRIFTWOOD BREWERY - DRIFTWOOD JUICY IPA TALL CAN": "flying-monkeys-juicy-ass-ipa-473ml",
  "ERDINGER - ALKOHOLFREI": "erdinger-alkoholfrei-500ml",
  "ESTRELLA DAMM TALL CAN": "estrella-damm-500ml",
  "FERNIE BREWING - HEADWALL HAZY PALE ALE CAN": "fairweather-hazy-pale-ale",
  "GUINNESS PUB DRAUGHT CAN": "guinness-pub-draught-440ml",
  "GUINNESS PUB DRAUGHT TALL CAN": "guinness-pub-draught-440ml",
  "HACKER PSCHORR MUNICH GOLD TALL CAN": "hacker-pschorr-munich-500ml",
  "HEINEKEN SILVER": "heineken-silver-330ml",
  "HEINEKEN SILVER - CAN": "heineken-silver-330ml",
  "HOLSTEN - MAIBOCK TALL CAN": "holsten-maibock-473ml",
  "INNIS & GUNN - THE ORIGINAL 4PK": "innis-and-gunn-original-473ml",
  "KILKENNY IRISH CREAM ALE DRAUGHT TALL CAN": "kilkenny-cream-ale-500ml",
  "KRONENBOURG - 1664 BLANC": "kronenbourg-1664-blanc-473ml",
  "KRONENBOURG - 1664 BLANC TALL CAN": "kronenbourg-1664-blanc-473ml",
  "LABATT - BUD LIGHT CAN": "bud-light",
  "LABATT - BUDWEISER ZERO": "budweiser-zero",
  "LABATT - BUSCH LIGHT CAN": "busch-light",
  "LABATT - KOKANEE CAN": "kokanee-355ml",
  "LABATT - MICHELOB ULTRA 6 CAN": "michelob-ultra",
  "LABATT - MICHELOB ULTRA CAN": "michelob-ultra",
  "LEFFE BLONDE": "leffe-blonde",
  "MICHELOB - ULTRA SLEEK 24 CAN": "michelob-ultra",
  "MICHELOB - ULTRA SLEEK CAN": "michelob-ultra",
  "MICHELOB - ULTRA SLEEK TALL CAN": "michelob-ultra",
  "MILLER GENUINE DRAFT": "miller-genuine-draft-355ml",
  "MILLER GENUINE DRAFT - CAN": "miller-genuine-draft-355ml",
  "MILLER HIGH LIFE": "miller-high-life-473ml",
  "MILLER HIGH LIFE - CAN": "miller-high-life-473ml",
  "MILLER LITE - CAN": "miller-lite-473ml",
  "MODELO - ESPECIAL CAN": "modelo-especial",
  "MODELO ESPECIAL": "modelo-especial",
  "MOLSON - CANADIAN CAN": "molson-canadian",
  "MOLSON CANADIAN": "molson-canadian",
  "MOLSON CANADIAN - CAN": "molson-canadian",
  "MOLSON CANADIAN - CAN TALL CAN": "molson-canadian",
  "NEGRA MODELO": "negra-modelo-355ml",
  "NELSON BREWING COMPANY - VALHALLA HAZY PALE ALE TALL CAN": "fairweather-hazy-pale-ale",
  "OLD STYLE PILSNER - CAN": "old-style-pilsner-473ml",
  "OLD STYLE PILSNER - TALL CAN": "old-style-pilsner-473ml",
  "PABST BLUE RIBBON - CAN": "pabst-blue-ribbon-473ml",
  "PARALLEL 49 - CRAFT LAGER LIME TALL CAN": "anderson-craft-ales-anderson-craft-ales-gold-lime-lager",
  "PARALLEL 49 - CRAFT PALE ALE TALL CAN": "anderson-craft-session-pale",
  "PARALLEL 49 - CRAFT PILSNER TALL CAN": "anderson-craft-ales-anderson-ales-summer-pilsner",
  "PARALLEL 49 - TRICYCLE GRAPEFRUIT RADLER TALL CAN": "waterloo-grapefruit-radler-473ml",
  "PAULANER - HEFE WEISSEBIER TALL CAN": "paulaner-hefe-weissbier-500ml",
  "PERONI - NASTRO AZZURRO CAN": "peroni",
  "PERONI NASTRO  AZZURRO TALL CAN": "peroni",
  "PERONI NASTRO AZZURRO": "peroni",
  "PILSNER URQUELL": "pilsner-urquell-330ml",
  "PILSNER URQUELL TALL CAN": "pilsner-urquell-330ml",
  "RADEBERGER - PILSNER CAN": "radeberger-berliner-pilsner",
  "RED RACER -  WEST COAST IPA CAN": "lone-pine-west-coast-ipa-473ml",
  "RED STRIPE": "red-stripe-330ml",
  "SLEEMAN - CLEAR 2.0 CAN": "sleeman-clear",
  "SLEEMAN - CLEAR CAN": "sleeman-clear",
  "SLEEMAN - HONEY BROWN LAGER": "sleeman-honey-brown-lager-341ml",
  "SLEEMAN - HONEY BROWN LAGER CAN": "sleeman-honey-brown-lager-341ml",
  "STANLEY PARK - SUNSETTER NON-ALCOHOLIC PEACH WHEAT ALE CAN": "sober-carpenter-wheat",
  "STANLEY PARK - TRAILHOPPER NON-ALCOHOLIC IPA CAN": "sober-carpenter-ipa",
  "STEAM WHISTLE - PILSNER TALL CAN": "steam-whistle-pilsner",
  "STEAMWORKS - HAZY PALE ALE CAN": "fairweather-hazy-pale-ale",
  "STELLA ARTOIS": "stella-artois",
  "STELLA ARTOIS - CAN": "stella-artois",
  "STELLA ARTOIS - TALL CAN": "stella-artois",
  "STRANGE FELLOWS BREWING - SCARAB SUPER DRY LAGER TALL CAN": "asahi-super-dry-330ml",
  "STROH - OLD MILWAUKEE JUMBO CAN": "old-milwaukee-473ml",
  "STROH CANADA - OLD MILWAUKEE CAN": "old-milwaukee-473ml",
  "STROH CANADA - OLD MILWAUKEE CANS": "old-milwaukee-473ml",
  "STROH CANADA - PABST BLUE RIBBON CAN": "pabst-blue-ribbon-473ml",
  "TUBORG GOLD - TALL CAN": "tuborg-gold-473ml",
  "YELLOW DOG BREWING - SQUIRREL CHASER HAZY PALE ALE CAN": "fairweather-hazy-pale-ale",
};

const BY_ID = new Map(ALCOHOL_PRODUCTS.map((p) => [p.id, p]));

/** Resolve a bc_liquor product_name to its matched curated beer, or null. Server-side. */
export function matchedCuratedBeer(bcProductName: string | null | undefined): AlcoholRankingProduct | null {
  if (!bcProductName) return null;
  const id = BC_BEER_MATCHES[bcProductName];
  return id ? BY_ID.get(id) ?? null : null;
}
