export type AlcoholCategory = "Light Beers" | "IPAs" | "Craft Lagers" | "Hard Seltzers" | "Ciders";

export const ALCOHOL_CATEGORIES: AlcoholCategory[] = ["Light Beers", "IPAs", "Craft Lagers", "Hard Seltzers", "Ciders"];

export type AlcoholRankingProduct = {
  id: string;
  category: AlcoholCategory;
  brand: string;
  name: string;
  abv: number;
  caloriesPerCan: number;
  carbsPerCan: number;
  additiveCount: number;
  /** 1–5 — how fitness-friendly this drink is to reach for regularly. */
  gorillaPour: number;
  /** Where to find it in Canadian retail. */
  availability: string;
};

// Curated from manufacturer nutrition disclosures and Open Food Facts records,
// normalized to a standard 355mL can (148mL for wine, 44mL for spirits — n/a here,
// every entry below is a malt beverage, cider, or seltzer sold in a 355–473mL can).
export const ALCOHOL_PRODUCTS: AlcoholRankingProduct[] = [
  // ───────── LIGHT BEERS ─────────
  {
    id: "coors-light",
    category: "Light Beers",
    brand: "Molson Coors",
    name: "Coors Light",
    abv: 4.2,
    caloriesPerCan: 102,
    carbsPerCan: 5,
    additiveCount: 0,
    gorillaPour: 4,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "bud-light",
    category: "Light Beers",
    brand: "Labatt / AB InBev",
    name: "Bud Light",
    abv: 4.2,
    caloriesPerCan: 110,
    carbsPerCan: 6.6,
    additiveCount: 0,
    gorillaPour: 4,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "michelob-ultra",
    category: "Light Beers",
    brand: "Labatt / AB InBev",
    name: "Michelob Ultra",
    abv: 4.2,
    caloriesPerCan: 95,
    carbsPerCan: 2.6,
    additiveCount: 0,
    gorillaPour: 5,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "sleeman-clear-2-0",
    category: "Light Beers",
    brand: "Sleeman Breweries",
    name: "Sleeman Clear 2.0",
    abv: 4.0,
    caloriesPerCan: 90,
    carbsPerCan: 2.1,
    additiveCount: 0,
    gorillaPour: 5,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "labatt-blue-light",
    category: "Light Beers",
    brand: "Labatt",
    name: "Labatt Blue Light",
    abv: 4.0,
    caloriesPerCan: 99,
    carbsPerCan: 3.2,
    additiveCount: 0,
    gorillaPour: 4,
    availability: "Beer Store & LCBO — wide availability",
  },

  // ───────── IPAs ─────────
  {
    id: "collective-arts-ransack-ipa",
    category: "IPAs",
    brand: "Collective Arts Brewing",
    name: "Ransack the Universe IPA",
    abv: 6.4,
    caloriesPerCan: 215,
    carbsPerCan: 17,
    additiveCount: 0,
    gorillaPour: 2,
    availability: "LCBO & Beer Store — select craft sets",
  },
  {
    id: "wellington-brewery-ipa",
    category: "IPAs",
    brand: "Wellington Brewery",
    name: "Wellington IPA",
    abv: 5.8,
    caloriesPerCan: 195,
    carbsPerCan: 16,
    additiveCount: 0,
    gorillaPour: 2,
    availability: "Ontario craft retailers & LCBO — select stores",
  },

  // ───────── CRAFT LAGERS ─────────
  {
    id: "heineken",
    category: "Craft Lagers",
    brand: "Heineken N.V.",
    name: "Heineken Original",
    abv: 5.0,
    caloriesPerCan: 142,
    carbsPerCan: 11,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "corona-extra",
    category: "Craft Lagers",
    brand: "Constellation Brands",
    name: "Corona Extra",
    abv: 4.6,
    caloriesPerCan: 148,
    carbsPerCan: 14,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "molson-canadian",
    category: "Craft Lagers",
    brand: "Molson Coors",
    name: "Molson Canadian",
    abv: 5.0,
    caloriesPerCan: 145,
    carbsPerCan: 12,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "stella-artois",
    category: "Craft Lagers",
    brand: "AB InBev",
    name: "Stella Artois",
    abv: 5.0,
    caloriesPerCan: 153,
    carbsPerCan: 12.5,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "guinness-draught",
    category: "Craft Lagers",
    brand: "Diageo",
    name: "Guinness Draught",
    abv: 4.2,
    caloriesPerCan: 125,
    carbsPerCan: 10,
    additiveCount: 1,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "kokanee",
    category: "Craft Lagers",
    brand: "Molson Coors",
    name: "Kokanee Glacier Beer",
    abv: 4.0,
    caloriesPerCan: 142,
    carbsPerCan: 12,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — strongest in Western Canada",
  },
  {
    id: "steam-whistle-pilsner",
    category: "Craft Lagers",
    brand: "Steam Whistle Brewing",
    name: "Steam Whistle Pilsner",
    abv: 5.0,
    caloriesPerCan: 142,
    carbsPerCan: 12,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "mill-street-organic",
    category: "Craft Lagers",
    brand: "Mill Street Brewery",
    name: "Mill Street Organic Lager",
    abv: 5.0,
    caloriesPerCan: 150,
    carbsPerCan: 13,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "beaus-all-natural-lug-tread",
    category: "Craft Lagers",
    brand: "Beau's All Natural",
    name: "Lug Tread Lagered Ale",
    abv: 5.2,
    caloriesPerCan: 150,
    carbsPerCan: 13,
    additiveCount: 0,
    gorillaPour: 3,
    availability: "LCBO & Beer Store — strongest in Ontario",
  },

  // ───────── HARD SELTZERS ─────────
  {
    id: "white-claw-black-cherry",
    category: "Hard Seltzers",
    brand: "Mark Anthony Brands",
    name: "White Claw Hard Seltzer (Black Cherry)",
    abv: 5.0,
    caloriesPerCan: 100,
    carbsPerCan: 2,
    additiveCount: 0,
    gorillaPour: 5,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "truly-hard-seltzer",
    category: "Hard Seltzers",
    brand: "Boston Beer Company",
    name: "Truly Hard Seltzer (Wild Berry)",
    abv: 5.0,
    caloriesPerCan: 100,
    carbsPerCan: 1,
    additiveCount: 0,
    gorillaPour: 5,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "pc-seltzer",
    category: "Hard Seltzers",
    brand: "President's Choice",
    name: "PC Hard Seltzer",
    abv: 5.0,
    caloriesPerCan: 95,
    carbsPerCan: 1.5,
    additiveCount: 0,
    gorillaPour: 5,
    availability: "LCBO — exclusive to Loblaw-affiliated retail",
  },
  {
    id: "motts-clamato-caesar",
    category: "Hard Seltzers",
    brand: "Mott's",
    name: "Mott's Clamato Caesar (Original, 6%)",
    abv: 6.0,
    caloriesPerCan: 150,
    carbsPerCan: 9,
    additiveCount: 1,
    gorillaPour: 3,
    availability: "Beer Store & LCBO — wide availability (canned RTD cocktail)",
  },

  // ───────── CIDERS ─────────
  {
    id: "strongbow-original-dry",
    category: "Ciders",
    brand: "Heineken / Strongbow",
    name: "Strongbow Original Dry Apple Cider",
    abv: 5.0,
    caloriesPerCan: 158,
    carbsPerCan: 16,
    additiveCount: 1,
    gorillaPour: 2,
    availability: "Beer Store & LCBO — wide availability",
  },
  {
    id: "growers-apple-cider",
    category: "Ciders",
    brand: "Growers Cider Co.",
    name: "Growers Apple Cider",
    abv: 6.0,
    caloriesPerCan: 190,
    carbsPerCan: 25,
    additiveCount: 1,
    gorillaPour: 1,
    availability: "Beer Store & LCBO — strongest in Western Canada",
  },
];
