import type { EvidenceTier } from "../../scan/lib/scoring";

export type Category =
  | "Creatine"
  | "Whey Protein"
  | "Pre-Workout"
  | "BCAAs/EAAs"
  | "Sleep & Recovery"
  | "Fish Oil & Omega-3"
  | "Greens Powders"
  | "Electrolytes"
  | "Collagen"
  | "Vitamins & Minerals";

export type Grade = "S" | "A+" | "A" | "B" | "C" | "D";

export type Product = {
  id: string;
  category: Category;
  name: string;
  brand: string;
  /** How settled the science is on the claims made about this product's category — e.g. creatine monohydrate is STRONG CONSENSUS, a newer blend is PRECAUTIONARY. */
  evidenceTier: EvidenceTier;
  /** ISO date this entry's data was last checked against current sources. */
  lastVerified: string;
  grade: Grade;
  pricePerServing: number;
  thirdPartyTested: boolean;
  purityScore: number;
  certifications: string[];
  analysis: string;
  pros: string[];
  cons: string[];
};

export const CATEGORIES: Category[] = [
  "Creatine",
  "Whey Protein",
  "Pre-Workout",
  "BCAAs/EAAs",
  "Sleep & Recovery",
  "Fish Oil & Omega-3",
  "Greens Powders",
  "Electrolytes",
  "Collagen",
  "Vitamins & Minerals",
];

export const GRADE_RANK: Record<Grade, number> = { S: 6, "A+": 5, A: 4, B: 3, C: 2, D: 1 };

export const GRADE_COLORS: Record<Grade, string> = {
  S: "#3ddc84",
  "A+": "#7be37b",
  A: "#ffd700",
  B: "#ffb84d",
  C: "#ff9d2e",
  D: "#ff4d4d",
};

export const GRADE_LEGEND: { grade: Grade; label: string; description: string }[] = [
  { grade: "S", label: "Elite", description: "Exceptional purity, full label transparency, independently verified. The benchmark." },
  { grade: "A+", label: "Excellent", description: "Near-flawless formulation and testing. Tiny nitpicks at most." },
  { grade: "A", label: "Very Good", description: "Strong, trustworthy product with minor caveats worth knowing." },
  { grade: "B", label: "Good", description: "Solid choice, but carries tradeoffs — dosing, sweeteners, or value." },
  { grade: "C", label: "Average", description: "Gets the job done. Expect some red flags: blends, fillers, or weak claims." },
  { grade: "D", label: "Below Average", description: "Proprietary blends, underdosed actives, or additive-heavy. Buyer beware." },
];

export const PRODUCTS: Product[] = [
  // ───────── CREATINE ─────────
  {
    id: "creatine-forge-micronized",
    category: "Creatine",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Micronized Creatine Monohydrate",
    brand: "Forge Labs",
    grade: "S",
    pricePerServing: 0.18,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["Creapure®", "Informed Sport", "NSF Certified for Sport"],
    analysis:
      "This is the gold standard, full stop. Creapure-sourced monohydrate, micronized for solubility, single-ingredient label, and triple-certified. There is nothing to hide here because there's nothing extra in the tub — just the most-researched ergogenic compound on the planet at clinical dosing.",
    pros: [
      "Single-ingredient label — exactly 5g creatine monohydrate, nothing else",
      "Creapure® certified for pharmaceutical-grade purity",
      "Third-party tested by two independent bodies",
      "Lowest cost-per-effective-dose in the category",
    ],
    cons: [
      "Unflavored — mixes with a slight chalkiness if under-stirred",
      "Tub design wastes a little space versus pouch competitors",
    ],
  },
  {
    id: "creatine-ironcore-hcl",
    category: "Creatine",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-01",
    name: "Creatine HCl Pro",
    brand: "IronCore",
    grade: "A",
    pricePerServing: 0.42,
    thirdPartyTested: true,
    purityScore: 95,
    certifications: ["Informed Sport"],
    analysis:
      "HCl formulations promise better solubility and lower bloat at smaller doses — and IronCore backs that up with a clean label and real testing. The catch is the price: you're paying roughly double per gram of creatine versus monohydrate for a solubility benefit most lifters won't notice.",
    pros: [
      "Smaller, more soluble dose with no loading phase needed",
      "Clean label — no fillers, dyes, or artificial sweeteners",
      "Independently tested for banned substances",
    ],
    cons: [
      "More than 2x the cost-per-gram of monohydrate for marginal benefit",
      "Less long-term research backing than monohydrate",
    ],
  },
  {
    id: "creatine-summit-blend",
    category: "Creatine",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-01",
    name: "Creatine Blend Matrix",
    brand: "Summit Nutrition",
    grade: "C",
    pricePerServing: 0.55,
    thirdPartyTested: false,
    purityScore: 71,
    certifications: [],
    analysis:
      "A 'multi-source creatine matrix' that mixes monohydrate with three exotic creatine forms in a proprietary blend — meaning you can't see how much of each you're actually getting. The underlying monohydrate dose looks underwhelming once you account for the filler forms padding the label.",
    pros: [
      "Includes a base of standard creatine monohydrate",
      "Capsule format is convenient for travel",
    ],
    cons: [
      "Proprietary blend hides individual ingredient amounts",
      "No third-party testing or purity certification",
      "Premium price for unproven 'advanced' creatine forms",
    ],
  },
  {
    id: "creatine-vantage-creapure",
    category: "Creatine",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Creapure® Elite",
    brand: "Vantage Performance",
    grade: "S",
    pricePerServing: 0.21,
    thirdPartyTested: true,
    purityScore: 98,
    certifications: ["Creapure®", "Informed Sport"],
    analysis:
      "Vantage doesn't reinvent the wheel — it just sources the best wheel available. German-made Creapure monohydrate, batch-tested, and priced fairly. If Forge Labs is the benchmark, this is the benchmark's closest competitor, separated only by a slightly higher price-per-serving.",
    pros: [
      "Creapure® sourced — independently verified for heavy metals and purity",
      "Transparent single-ingredient formula",
      "Informed Sport certified for competitive athletes",
    ],
    cons: [
      "Slightly pricier than Forge Labs for an equivalent product",
      "No flavored options available",
    ],
  },

  // ───────── WHEY PROTEIN ─────────
  {
    id: "whey-bedrock-grassfed-isolate",
    category: "Whey Protein",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Grass-Fed Whey Isolate",
    brand: "Bedrock Nutrition",
    grade: "S",
    pricePerServing: 1.35,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["Informed Sport", "Grass Fed Certified", "NSF Certified for Sport"],
    analysis:
      "27g of protein per scoop, sub-1g sugar, no artificial sweeteners, and grass-fed sourcing that's actually verified — not just printed on the label. This is what 'premium' is supposed to mean. The scoring reflects a near-perfect amino profile with zero flagged additives in the ingredient scan.",
    pros: [
      "27g protein, <1g sugar, <1g fat per serving — elite macros",
      "Naturally sweetened with stevia leaf extract, no artificial dyes",
      "Third-party verified grass-fed sourcing and banned-substance testing",
    ],
    cons: [
      "Among the most expensive options per serving in this roundup",
      "Limited flavor lineup compared to mass-market brands",
    ],
  },
  {
    id: "whey-granite-gold-standard",
    category: "Whey Protein",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Gold Standard Whey Blend",
    brand: "Granite Supplements",
    grade: "A",
    pricePerServing: 0.95,
    thirdPartyTested: true,
    purityScore: 90,
    certifications: ["Informed Sport"],
    analysis:
      "A whey concentrate/isolate blend that hits a strong protein-per-dollar ratio without cutting corners on testing. Sugar content creeps slightly into flagged territory in the chocolate variants, but the overall additive profile stays clean. A genuinely solid daily driver.",
    pros: [
      "Strong 24g protein per serving at a mid-range price point",
      "Third-party tested for purity and banned substances",
      "Mixes smoothly without a gritty aftertaste",
    ],
    cons: [
      "Chocolate flavors run slightly higher in sugar (~13g/serving)",
      "Contains sucralose, which some users prefer to avoid",
    ],
  },
  {
    id: "whey-crucible-mass",
    category: "Whey Protein",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Mass Whey Concentrate",
    brand: "Crucible Labs",
    grade: "C",
    pricePerServing: 0.78,
    thirdPartyTested: false,
    purityScore: 68,
    certifications: [],
    analysis:
      "Marketed as a 'mass gainer protein,' which mostly means extra maltodextrin and sugar riding alongside a modest protein dose. The ingredient scan flags both elevated sugar and two additives used purely for mouthfeel and shelf life — neither doing the consumer any favors.",
    pros: [
      "Higher calorie content suits genuine bulking goals",
      "Widely available at most major retailers",
    ],
    cons: [
      "16g of sugar per serving — well into flagged territory",
      "Contains carrageenan and sucralose with no testing certification",
      "Protein-to-calorie ratio is weak for the price",
    ],
  },
  {
    id: "whey-anvil-clean-isolate",
    category: "Whey Protein",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Clean Isolate 90",
    brand: "Anvil Performance",
    grade: "A+",
    pricePerServing: 1.18,
    thirdPartyTested: true,
    purityScore: 96,
    certifications: ["Informed Sport", "NSF Certified for Sport"],
    analysis:
      "A 90%+ pure whey protein isolate with an almost suspiciously short ingredient list — and that's the point. Minimal processing aids, no dyes, no flagged sweeteners, and a verified amino acid profile that backs up every gram on the label. One of the cleanest isolates we've scored.",
    pros: [
      "90%+ pure isolate with verified amino acid profile",
      "Zero flagged additives detected in ingredient scan",
      "Low lactose — well tolerated by sensitive stomachs",
    ],
    cons: [
      "Thinner texture than concentrate-based blends",
      "Premium pricing puts it out of reach for budget stacks",
    ],
  },
  {
    id: "whey-outlaw-budget-stack",
    category: "Whey Protein",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-01",
    name: "Budget Whey Stack",
    brand: "Outlaw Nutrition",
    grade: "D",
    pricePerServing: 0.52,
    thirdPartyTested: false,
    purityScore: 54,
    certifications: [],
    analysis:
      "The cheapest whey on this list — and it shows. Heavy on maltodextrin filler, light on actual protein per scoop, and the ingredient scan turns up three flagged additives including a high-risk synthetic dye. This is a sports-drink-adjacent product wearing a protein label.",
    pros: [
      "Lowest price point in the entire roundup",
      "Sweet flavor profile that masks poor mixability",
    ],
    cons: [
      "Only 14g of actual protein despite a 30g scoop size",
      "Contains Sunset Yellow FCF (E110) — a flagged high-risk dye",
      "High sugar content and zero independent testing",
    ],
  },

  // ───────── PRE-WORKOUT ─────────
  {
    id: "pre-catalyst-ignite",
    category: "Pre-Workout",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-01",
    name: "Ignite Pre",
    brand: "Catalyst Labs",
    grade: "B",
    pricePerServing: 1.05,
    thirdPartyTested: true,
    purityScore: 84,
    certifications: ["Informed Sport"],
    analysis:
      "A competently dosed stim-based pre-workout — 200mg caffeine, clinical-range citrulline malate, and full label transparency on every active. It loses points for a couple of cosmetic additives that add nothing functionally, but the core formula does what it says on the tin.",
    pros: [
      "Fully disclosed dosages — no proprietary blends",
      "200mg caffeine plus 6g citrulline malate at clinical levels",
      "Third-party tested for banned substances",
    ],
    cons: [
      "Contains sucralose and a synthetic color additive",
      "Caffeine load may be high for stim-sensitive users",
    ],
  },
  {
    id: "pre-vertex-surge",
    category: "Pre-Workout",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-01",
    name: "Surge V2",
    brand: "Vertex Athletics",
    grade: "S",
    pricePerServing: 1.22,
    thirdPartyTested: true,
    purityScore: 98,
    certifications: ["Informed Sport", "NSF Certified for Sport", "Banned Substance Tested"],
    analysis:
      "Everything a pre-workout should be: fully dosed actives at the amounts shown in clinical trials, naturally flavored and colored, and triple-tested for banned substances. No proprietary blends, no synthetic dyes, no filler. This is the rare formula engineered for performance over marketing.",
    pros: [
      "Every active dosed at or above clinically studied amounts",
      "Naturally flavored and colored — zero flagged additives",
      "Triple-certified for competitive and tested athletes",
    ],
    cons: [
      "Among the priciest pre-workouts per serving",
      "Strong natural flavor profile — an acquired taste for some",
    ],
  },
  {
    id: "pre-strata-rocket-fuel",
    category: "Pre-Workout",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-01",
    name: "Rocket Fuel Extreme",
    brand: "Strata Sport",
    grade: "D",
    pricePerServing: 0.98,
    thirdPartyTested: false,
    purityScore: 49,
    certifications: [],
    analysis:
      "Hides its entire active ingredient list behind a 'Rocket Fuel Proprietary Complex,' so there's no way to verify the caffeine dose — and anecdotal reports suggest it's substantial. The ingredient scan flags four additives, including two synthetic dyes and a preservative linked to nitrosamine formation.",
    pros: [
      "Strong stimulant effect reported by users",
      "Wide flavor variety",
    ],
    cons: [
      "Proprietary blend conceals all dosages, including caffeine",
      "Four flagged additives detected, two of them high-risk dyes",
      "No third-party testing — risky for tested athletes",
    ],
  },
  {
    id: "pre-apex-clean-charge",
    category: "Pre-Workout",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-01",
    name: "Clean Charge",
    brand: "Apex Labs",
    grade: "A",
    pricePerServing: 1.10,
    thirdPartyTested: true,
    purityScore: 92,
    certifications: ["Informed Sport"],
    analysis:
      "Built around a moderate 150mg caffeine dose plus beta-alanine and L-theanine for a smoother curve without the crash. Every ingredient is disclosed and dosed sensibly, and the additive scan comes back essentially clean — only a trace natural flavoring agent registers at all.",
    pros: [
      "Balanced 150mg caffeine + L-theanine — smooth energy, no crash",
      "Fully transparent label with clinically-informed dosing",
      "Virtually no flagged additives detected",
    ],
    cons: [
      "Lower stimulant ceiling won't satisfy heavy stim users",
      "Beta-alanine tingles are noticeable at full dose",
    ],
  },

  // ───────── BCAAs / EAAs ─────────
  {
    id: "amino-nordic-recovery",
    category: "BCAAs/EAAs",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-01",
    name: "Recovery Aminos Complete",
    brand: "Nordic Strength",
    grade: "A",
    pricePerServing: 0.88,
    thirdPartyTested: true,
    purityScore: 91,
    certifications: ["Informed Sport"],
    analysis:
      "A full essential amino acid spectrum (not just the three BCAAs) at research-backed ratios, naturally sweetened, and independently verified. It edges out most of the category by actually delivering what amino supplements promise — better recovery signaling via complete EAA coverage.",
    pros: [
      "Complete EAA profile, not just isolated BCAAs",
      "Naturally sweetened with stevia — no flagged sweeteners",
      "Verified amino acid ratios via third-party lab testing",
    ],
    cons: [
      "Mild aftertaste some users find off-putting",
      "Pricier than basic BCAA-only formulas",
    ],
  },
  {
    id: "amino-titan-bcaa-classic",
    category: "BCAAs/EAAs",
    evidenceTier: "contested",
    lastVerified: "2026-06-01",
    name: "BCAA 2:1:1 Classic",
    brand: "Titan Supps",
    grade: "C",
    pricePerServing: 0.61,
    thirdPartyTested: false,
    purityScore: 70,
    certifications: [],
    analysis:
      "A textbook 2:1:1 BCAA ratio with nothing to write home about — and nothing alarming either, beyond an artificial sweetener that lands a mild flag. The bigger issue is value: emerging research increasingly favors full EAA formulas over isolated BCAAs for the same money.",
    pros: [
      "Classic, well-studied 2:1:1 leucine-to-isoleucine-to-valine ratio",
      "Affordable entry point for amino supplementation",
    ],
    cons: [
      "Contains sucralose and an artificial color additive",
      "BCAA-only formula — increasingly seen as inferior to full EAA blends",
      "No independent purity testing",
    ],
  },
  {
    id: "amino-purestack-eaa",
    category: "BCAAs/EAAs",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-01",
    name: "EAA Essentials",
    brand: "PureStack",
    grade: "A+",
    pricePerServing: 0.97,
    thirdPartyTested: true,
    purityScore: 95,
    certifications: ["Informed Sport", "NSF Certified for Sport"],
    analysis:
      "All nine essential amino acids at fully disclosed amounts, sweetened naturally, double-certified, and not a single flagged additive in the scan. The formula mirrors what the clinical literature actually supports rather than chasing trends — a quietly excellent product.",
    pros: [
      "All 9 essential amino acids at disclosed clinical ratios",
      "Zero flagged additives — naturally sweetened and flavored",
      "Double-certified for purity and banned substances",
    ],
    cons: [
      "Higher price point than BCAA-only competitors",
      "Subtle flavor that some find too mild",
    ],
  },
  {
    id: "amino-brawn-sweetened-punch",
    category: "BCAAs/EAAs",
    evidenceTier: "contested",
    lastVerified: "2026-06-01",
    name: "Sweetened BCAA Punch",
    brand: "Brawn & Co",
    grade: "D",
    pricePerServing: 0.59,
    thirdPartyTested: false,
    purityScore: 51,
    certifications: [],
    analysis:
      "Reads more like a flavored drink mix than an amino supplement — the BCAA dose is on the low end of effective, while sugar and synthetic dye content push two separate flags in the scan. You're mostly paying for flavoring here, with aminos as an afterthought.",
    pros: [
      "Pleasant, candy-like flavor profile",
      "Low price point per serving",
    ],
    cons: [
      "Underdosed BCAAs relative to studied effective amounts",
      "Contains both Allura Red AC (E129) and added sugar above flag thresholds",
      "No third-party testing or certification",
    ],
  },

  // ───────── SLEEP & RECOVERY ─────────
  {
    id: "sleep-thorne-magnesium-bisglycinate",
    category: "Sleep & Recovery",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Magnesium Bisglycinate",
    brand: "Thorne Research",
    grade: "S",
    pricePerServing: 0.38,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["NSF Certified for Sport", "Informed Sport"],
    analysis:
      "Magnesium deficiency is rampant in athletes and directly degrades sleep quality — this is the fix. Bisglycinate is the most bioavailable form, Thorne's manufacturing is pharmaceutical-grade, and the NSF Certified for Sport stamp means a tested athlete can take it without career risk. No fillers, no proprietary nonsense, just the mineral your body actually needs.",
    pros: [
      "Bisglycinate form — highest bioavailability, minimal GI side effects",
      "NSF Certified for Sport: safe for all competitive levels",
      "No fillers, dyes, or artificial sweeteners",
      "Supports sleep latency, muscle relaxation, and overnight recovery",
    ],
    cons: [
      "Capsule-only — no powder option for stacking with other compounds",
      "Slightly pricier than oxide-form magnesium (which you should avoid anyway)",
    ],
  },
  {
    id: "sleep-legion-lunar",
    category: "Sleep & Recovery",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Lunar Sleep Aid",
    brand: "Legion Athletics",
    grade: "A+",
    pricePerServing: 1.08,
    thirdPartyTested: true,
    purityScore: 96,
    certifications: ["Informed Sport"],
    analysis:
      "Legion actually publishes its clinical dosing rationale, which is rare in the sleep supplement space. 30mg ashwagandha KSM-66, glycine, and L-theanine at evidence-backed amounts — no melatonin overdosing, no diphenhydramine, no antihistamine hangover. One of the few sleep products built around recovery rather than sedation.",
    pros: [
      "All active ingredients dosed at clinically studied amounts — no underdosing",
      "Avoids sedative antihistamines that impair REM and leave grogginess",
      "Full label transparency with published ingredient rationale",
      "Independently tested for banned substances",
    ],
    cons: [
      "No melatonin — may not suit users who respond specifically to it",
      "Higher cost than basic magnesium-only options",
    ],
  },
  {
    id: "sleep-transparent-labs-sleep",
    category: "Sleep & Recovery",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Sleep & Recovery Formula",
    brand: "Transparent Labs",
    grade: "A",
    pricePerServing: 0.89,
    thirdPartyTested: true,
    purityScore: 93,
    certifications: ["Informed Sport"],
    analysis:
      "The name says what it is and the label matches. Magnesium glycinate, L-theanine, and melatonin at a conservative 0.5mg dose — not the 5–10mg megadose that disrupts circadian rhythm regulation. Transparent Labs earns its brand name here with fully disclosed amounts on every ingredient.",
    pros: [
      "Conservative 0.5mg melatonin — avoids receptor desensitization",
      "Clean label with no flagged additives",
      "Full spectrum: covers relaxation, sleep onset, and overnight mineral needs",
    ],
    cons: [
      "Some users need a higher melatonin dose for jet lag or shift work",
      "Mild, unflavored capsule format — no powder option",
    ],
  },
  {
    id: "sleep-natural-stacks-magtech",
    category: "Sleep & Recovery",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "MagTech Magnesium Complex",
    brand: "Natural Stacks",
    grade: "A",
    pricePerServing: 0.72,
    thirdPartyTested: true,
    purityScore: 90,
    certifications: ["Informed Sport"],
    analysis:
      "Stacks three magnesium forms — glycinate for sleep, malate for energy metabolism, and threonate for cognitive function. The trifecta approach has theoretical merit: different forms concentrate in different tissues. Threonate in particular has credible emerging research on brain bioavailability. Costs more than mono-form options but covers more bases.",
    pros: [
      "Triple-form stack covers sleep, recovery, and cognitive function",
      "Magnesium threonate form — unique brain-penetrating bioavailability data",
      "Independently certified for banned substances",
    ],
    cons: [
      "Threonate research is promising but still early-stage",
      "Higher cost per elemental-mg of magnesium than single-form products",
    ],
  },
  {
    id: "sleep-now-gaba",
    category: "Sleep & Recovery",
    evidenceTier: "contested",
    lastVerified: "2026-06-08",
    name: "GABA 500mg",
    brand: "NOW Foods",
    grade: "B",
    pricePerServing: 0.14,
    thirdPartyTested: true,
    purityScore: 88,
    certifications: ["Informed Sport"],
    analysis:
      "Cheap, clean, and third-party tested. The controversy around GABA is real: oral GABA's ability to cross the blood-brain barrier is still debated in the literature. That said, some users report measurable relaxation response and NOW Foods is one of the most consistently clean budget supplement brands available.",
    pros: [
      "Exceptional value — among the lowest cost per dose in the category",
      "NOW Foods quality manufacturing with independent testing",
      "Clean, single-ingredient, no artificial additives",
    ],
    cons: [
      "Blood-brain barrier penetration of oral GABA remains scientifically contested",
      "Individual response varies widely — works for some, not others",
    ],
  },
  {
    id: "sleep-momentous-elite-sleep",
    category: "Sleep & Recovery",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Elite Sleep",
    brand: "Momentous",
    grade: "A+",
    pricePerServing: 1.50,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["NSF Certified for Sport", "Informed Sport"],
    analysis:
      "Momentous built this for elite professional athletes — the certifications list reflects it. Phosphatidylserine, apigenin, and magnesium threonate in evidence-backed doses. No melatonin, no antihistamines, just compounds with credible mechanisms for improving deep sleep architecture and overnight cortisol management.",
    pros: [
      "Double-certified: NSF Certified for Sport and Informed Sport",
      "Apigenin and phosphatidylserine target cortisol and sleep architecture",
      "Trusted by professional sports teams and Olympic programs",
    ],
    cons: [
      "Most expensive sleep product in this roundup",
      "Some ingredients have limited standalone RCT data",
    ],
  },
  {
    id: "sleep-natrol-melatonin-10mg",
    category: "Sleep & Recovery",
    evidenceTier: "contested",
    lastVerified: "2026-06-08",
    name: "Melatonin 10mg Fast Dissolve",
    brand: "Natrol",
    grade: "C",
    pricePerServing: 0.08,
    thirdPartyTested: false,
    purityScore: 62,
    certifications: [],
    analysis:
      "The 10mg melatonin dose is the problem. Regulatory-grade sleep research shows 0.3–1mg is effective for circadian rhythm support — 10mg is ten to thirty times that dose and is associated with next-day grogginess, hormonal receptor downregulation, and disrupted REM. This product is everywhere at pharmacies and almost entirely wrong for the purpose.",
    pros: [
      "Extremely cheap and widely available",
      "Fast-dissolve format has rapid absorption",
    ],
    cons: [
      "10mg dose is 10–30x higher than what research supports for circadian signaling",
      "Chronic high-dose melatonin may downregulate endogenous melatonin production",
      "No third-party testing — label accuracy unverified",
    ],
  },
  {
    id: "sleep-olly-sleep-gummy",
    category: "Sleep & Recovery",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Sleep Gummies",
    brand: "OLLY",
    grade: "D",
    pricePerServing: 0.32,
    thirdPartyTested: false,
    purityScore: 44,
    certifications: [],
    analysis:
      "Candy with melatonin. Sugar, corn syrup, synthetic colors, and gelling agents dominate the label before you get to the actual active ingredient. The lemon-balm and L-theanine doses are so far below studied effective amounts they function as marketing decoration. This is a product designed to sell on the shelf, not to optimize recovery.",
    pros: [
      "Pleasant taste — high compliance for melatonin skeptics",
      "Accessible at grocery and drug stores",
    ],
    cons: [
      "Loaded with sugar, corn syrup, and synthetic color additives",
      "L-theanine and lemon balm are severely underdosed",
      "Zero third-party testing — gummy supplements are notoriously inaccurate for potency",
    ],
  },
  {
    id: "sleep-klean-athlete-recovery",
    category: "Sleep & Recovery",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Recovery Formula",
    brand: "Klean Athlete",
    grade: "A",
    pricePerServing: 0.95,
    thirdPartyTested: true,
    purityScore: 94,
    certifications: ["NSF Certified for Sport"],
    analysis:
      "Targets overnight muscle recovery specifically: tart cherry extract for inflammation modulation, L-glutamine, and magnesium glycinate. The tart cherry research is credible — multiple trials show reduced muscle soreness and improved sleep quality in athletes. NSF Certified for Sport makes it safe for competitive use.",
    pros: [
      "Tart cherry extract has legitimate RCT data for athlete recovery",
      "NSF Certified for Sport — trusted by professional organizations",
      "Targets both sleep quality and muscle recovery, not just sedation",
    ],
    cons: [
      "Tart cherry extract sourcing and concentration vary by batch",
      "Not a sedative — may disappoint users looking for knock-out effect",
    ],
  },
  {
    id: "sleep-dream-water-snooz",
    category: "Sleep & Recovery",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Snooz Sleep Shot",
    brand: "Dream Water",
    grade: "D",
    pricePerServing: 2.40,
    thirdPartyTested: false,
    purityScore: 38,
    certifications: [],
    analysis:
      "A $2.40 liquid sleep shot with a 5mg melatonin dose, artificial flavoring, added sugar, and preservatives. The novel liquid format adds cost while the formula adds risk — 5mg melatonin is still far above evidence-based dosing, and the additive load turns a simple micronutrient into a chemistry experiment.",
    pros: [
      "Convenient, portable single-serve format",
      "Fast absorption compared to capsules",
    ],
    cons: [
      "5mg melatonin — five to fifteen times the studied effective dose",
      "Artificial flavors and preservatives add unnecessary additive load",
      "No third-party testing at a premium price point",
    ],
  },

  // ───────── FISH OIL & OMEGA-3 ─────────
  {
    id: "fishoil-nordic-ultimate-omega",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Ultimate Omega 2X",
    brand: "Nordic Naturals",
    grade: "S",
    pricePerServing: 0.65,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["IFOS 5-Star", "NSF Certified for Sport", "Friend of the Sea"],
    analysis:
      "The benchmark in fish oil. Nordic Naturals publishes third-party IFOS testing results by batch — you can look up your lot number and verify EPA/DHA content and oxidation levels yourself. Triglyceride form (not ethyl ester) means better absorption, and the concentrated 2X formula means fewer soft gels to swallow.",
    pros: [
      "IFOS 5-Star certified — highest industry standard for purity and potency",
      "Triglyceride form: 25–70% better absorption than ethyl ester forms",
      "Published batch-by-batch third-party lab results available online",
      "Low oxidation levels — fresh oil with no fishy aftertaste",
    ],
    cons: [
      "Among the pricier fish oils per gram of EPA+DHA",
      "Soft gel format only — no liquid option in this product line",
    ],
  },
  {
    id: "fishoil-carlson-norwegian",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "The Very Finest Fish Oil",
    brand: "Carlson Labs",
    grade: "A+",
    pricePerServing: 0.42,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["IFOS Certified", "Friend of the Sea"],
    analysis:
      "Carlson has been making fish oil since 1965 and the liquid format is one of the best delivery mechanisms available — no oxidation from encapsulation, easy dose adjustment, and excellent value per gram of omega-3. Norwegian-sourced small pelagic fish means lower heavy metal load than large predatory species.",
    pros: [
      "Liquid format — highest bioavailability, easy dose adjustment",
      "Norwegian small-catch sourcing minimizes mercury exposure",
      "IFOS certified with decades of quality track record",
      "Lemon flavor masks fish taste effectively",
    ],
    cons: [
      "Liquid format requires refrigeration after opening",
      "Less portable than soft gels for travel",
    ],
  },
  {
    id: "fishoil-thorne-super-epa",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Super EPA",
    brand: "Thorne Research",
    grade: "S",
    pricePerServing: 0.72,
    thirdPartyTested: true,
    purityScore: 98,
    certifications: ["NSF Certified for Sport", "IFOS Certified"],
    analysis:
      "EPA-dominant formulation targeting inflammation and cardiovascular health specifically, with a higher EPA:DHA ratio than most standard fish oils. Thorne's manufacturing is the closest you get to pharmaceutical-grade in the supplement industry. NSF Certified for Sport makes this the safe choice for professional and competitive athletes.",
    pros: [
      "High EPA concentration — targets inflammation and cardiovascular health",
      "NSF Certified for Sport — trusted by Olympic programs",
      "Thorne's quality manufacturing consistently passes independent audits",
    ],
    cons: [
      "EPA-heavy ratio may not suit users who need more DHA for cognitive support",
      "Premium pricing versus comparable IFOS-certified products",
    ],
  },
  {
    id: "fishoil-sports-research-triglyceride",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Omega-3 Triple Strength",
    brand: "Sports Research",
    grade: "A+",
    pricePerServing: 0.35,
    thirdPartyTested: true,
    purityScore: 95,
    certifications: ["IFOS 5-Star", "Informed Sport"],
    analysis:
      "Best value-to-quality ratio in the category. Triple-strength triglyceride form means one soft gel delivers what cheap formulas take three to provide, the IFOS 5-Star certification is the hardest standard to earn, and the price-per-gram of EPA+DHA is difficult to beat with equivalent quality.",
    pros: [
      "Exceptional value — highest quality-per-dollar in this roundup",
      "IFOS 5-Star and Informed Sport dual certification",
      "Triglyceride form for superior absorption vs. standard ethyl ester",
    ],
    cons: [
      "Large soft gel size can be difficult to swallow",
      "Mild fish aftertaste with some batches",
    ],
  },
  {
    id: "fishoil-viva-omega3-dha",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Omega-3 DHA 500",
    brand: "Viva Naturals",
    grade: "A",
    pricePerServing: 0.28,
    thirdPartyTested: true,
    purityScore: 91,
    certifications: ["IFOS Certified", "Non-GMO Project Verified"],
    analysis:
      "DHA-dominant formula suited for cognitive health, vision support, and pregnancy — areas where DHA's role is better established than EPA. Budget-friendly price and IFOS certification make this a strong recommendation for anyone who doesn't need the inflammation-targeting EPA profile.",
    pros: [
      "High DHA concentration supports brain, eye, and neurological health",
      "IFOS certified at a budget-friendly price point",
      "Well-tolerated — low fishy aftertaste reported",
    ],
    cons: [
      "Lower EPA content may not adequately support inflammation management",
      "Ethyl ester form — slightly lower absorption than triglyceride",
    ],
  },
  {
    id: "fishoil-kirkland-omega3",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Omega-3 1000mg",
    brand: "Kirkland Signature",
    grade: "B",
    pricePerServing: 0.05,
    thirdPartyTested: true,
    purityScore: 82,
    certifications: ["USP Verified"],
    analysis:
      "The cheapest third-party tested fish oil available. USP Verified is a legitimate certification — it confirms label accuracy and absence of contaminants, though it doesn't test the full IFOS spectrum including oxidation. At $0.05 per serving, the value is extraordinary. The catch is you need two to three soft gels to hit meaningful EPA+DHA levels.",
    pros: [
      "Lowest cost per serving of any certified fish oil in this roundup",
      "USP Verified — confirms label accuracy for heavy metals and potency",
      "Widely available in Canada at Costco",
    ],
    cons: [
      "Standard 300mg EPA+DHA per gel — need 2–3 for therapeutic dosing",
      "Ethyl ester form with moderate absorption",
      "Not IFOS certified — oxidation levels not independently verified",
    ],
  },
  {
    id: "fishoil-garden-of-life-algae",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Oceans 3 Algae Omega-3",
    brand: "Garden of Life",
    grade: "A+",
    pricePerServing: 0.88,
    thirdPartyTested: true,
    purityScore: 96,
    certifications: ["IFOS Certified", "NSF Certified for Sport", "Certified Vegan", "Non-GMO Project Verified"],
    analysis:
      "Algae-sourced omega-3 is the cleanest possible origin — no mercury accumulation, no ocean contaminants, and no ecological footprint from fishing. The algae is where fish get their omega-3 from anyway, so you're getting the same fatty acids with zero downstream bioaccumulation risk. Ideal for vegans and anyone with heavy metal concerns.",
    pros: [
      "Algae source — zero heavy metal risk, lowest ecological footprint",
      "Vegan-certified and suitable for all dietary preferences",
      "Same EPA/DHA profile as fish oil without bioaccumulation concerns",
      "IFOS certified and NSF Certified for Sport",
    ],
    cons: [
      "Highest cost per gram of EPA+DHA in this category",
      "Algae farming has its own sustainability considerations at scale",
    ],
  },
  {
    id: "fishoil-igenics-bargain-oil",
    category: "Fish Oil & Omega-3",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Omega-3 Complex",
    brand: "Nature's Bounty",
    grade: "C",
    pricePerServing: 0.09,
    thirdPartyTested: false,
    purityScore: 61,
    certifications: [],
    analysis:
      "A widely distributed mass-market fish oil without independent purity verification. The label lists EPA+DHA but no third party confirms it matches. Consumer Lab testing of similar products in this tier has found oxidation levels that exceed industry guidelines. Cheap, but the unknowns are real.",
    pros: [
      "Widely available and extremely affordable",
      "Meets basic FDA manufacturing standards",
    ],
    cons: [
      "No IFOS or equivalent purity certification",
      "Independent testing has flagged oxidation concerns in this product tier",
      "Label accuracy unverified",
    ],
  },
  {
    id: "fishoil-nutrigold-triple-strength",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Triple Strength Omega-3 Gold",
    brand: "NutriGold",
    grade: "A+",
    pricePerServing: 0.45,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["IFOS 5-Star", "Non-GMO Project Verified", "Friend of the Sea"],
    analysis:
      "Triple-strength concentrate means one soft gel hits 1,500mg EPA+DHA — reducing the daily soft gel count to one. IFOS 5-Star certification is the gold standard for fish oil verification. NutriGold publishes CoA documents for each batch. A genuinely excellent product that competes directly with Nordic Naturals at a lower price.",
    pros: [
      "One-per-day convenience — 1500mg EPA+DHA per single soft gel",
      "IFOS 5-Star: highest independently verified standard in fish oil",
      "Published batch CoA documents for full transparency",
    ],
    cons: [
      "Large soft gel size — may require splitting dose for easier swallowing",
      "Slightly harder to find in Canadian retail vs. US",
    ],
  },
  {
    id: "fishoil-barleans-liquid",
    category: "Fish Oil & Omega-3",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Ideal Omega-3 Liquid",
    brand: "Barlean's",
    grade: "A",
    pricePerServing: 0.55,
    thirdPartyTested: true,
    purityScore: 92,
    certifications: ["IFOS Certified", "Non-GMO Project Verified"],
    analysis:
      "A smooth-emulsified liquid fish oil that masks taste better than most — useful for anyone who struggles with fish oil compliance. IFOS certified, Norwegian-sourced, and the emulsification process may improve absorption compared to standard liquid oils. A strong daily driver for compliance-challenged users.",
    pros: [
      "Emulsified format — smoother taste, potentially improved bioavailability",
      "IFOS certified with Norwegian small-fish sourcing",
      "High palatability improves long-term supplementation compliance",
    ],
    cons: [
      "Emulsification additives (lecithin, natural flavors) add minor complexity",
      "Requires refrigeration and use within 45 days of opening",
    ],
  },

  // ───────── GREENS POWDERS ─────────
  {
    id: "greens-ag1-athletic-greens",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "AG1",
    brand: "Athletic Greens",
    grade: "C",
    pricePerServing: 2.63,
    thirdPartyTested: true,
    purityScore: 72,
    certifications: ["NSF Certified for Sport", "Informed Sport"],
    analysis:
      "AG1 has the certifications, the ingredient list, and the marketing machine — but at $2.63+ per serving, it fails the value test badly. The formula is real: spirulina, ashwagandha, probiotics, and digestive enzymes are all credible inclusions. But virtually every key ingredient hides inside a 'Alkalising Greens Complex' or 'Nutrient Dense Natural Extracts Blend' — meaning the actual doses are undisclosed. You cannot verify whether ashwagandha is at 300mg KSM-66 (effective) or 30mg (marketing). The NSF cert verifies what's in the product, not that what's in it is dosed correctly. For $2.63 per day you could buy a Creapure creatine, a clinical omega-3, and a magnesium glycinate — all at verified doses, all with stronger evidence bases. AG1 is a well-marketed greens cocktail at a venture-capital price.",
    pros: [
      "NSF Certified for Sport and Informed Sport — tested for banned substances",
      "75-ingredient formula covers multiple nutritional bases in one scoop",
      "Probiotics and digestive enzymes are legitimate functional additions",
      "Tastes better than most greens powders",
    ],
    cons: [
      "Proprietary blends hide individual ingredient dosing — efficacy unverifiable",
      "At $2.63+/serving, dramatically worse value than targeted individual supplements",
      "Heavy marketing spend inflates price without improving formulation",
      "Most claimed benefits are duplicated by diet, protein powder, or single-ingredient supplements",
    ],
  },
  {
    id: "greens-organifi-green-juice",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Green Juice",
    brand: "Organifi",
    grade: "B",
    pricePerServing: 2.05,
    thirdPartyTested: true,
    purityScore: 80,
    certifications: ["Informed Sport", "USDA Organic"],
    analysis:
      "Organifi earns points for organic certification and a relatively shorter ingredient list than most greens powders — fewer ingredients, more potential for actual dosing. Ashwagandha, moringa, chlorella, and matcha form the core. Still hides amounts behind a proprietary blend, but the lower ingredient count means those doses can be higher per compound. Better than most, still not transparent.",
    pros: [
      "USDA Organic certification — no synthetic pesticide residue",
      "Shorter ingredient list improves odds of meaningful individual dosing",
      "Informed Sport certified for athletes",
      "Pleasant taste with matcha base",
    ],
    cons: [
      "Proprietary blend still hides individual ingredient amounts",
      "At $2.05/serving, expensive relative to individual organic supplements",
      "Limited prebiotic and probiotic content vs. competitors",
    ],
  },
  {
    id: "greens-amazing-grass-green-superfood",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Green Superfood",
    brand: "Amazing Grass",
    grade: "B",
    pricePerServing: 0.78,
    thirdPartyTested: true,
    purityScore: 77,
    certifications: ["Informed Sport", "USDA Organic", "Non-GMO Project Verified"],
    analysis:
      "The best price-to-legitimacy ratio in the greens category. Whole-leaf grass powders (wheatgrass, barley grass, spirulina), USDA Organic certified, and Informed Sport tested. The formula isn't trying to be a multivitamin — it's a greens concentrate, and at that stated purpose it delivers credibly. Proprietary blends are still present, but the lower overall price makes the value equation work.",
    pros: [
      "USDA Organic and Informed Sport certified at an accessible price",
      "Whole-leaf grasses over extract concentrates — less processed",
      "No proprietary superblend tricks — relatively transparent for the category",
    ],
    cons: [
      "Grassy taste is polarizing — better with fruit juice than water",
      "Some proprietary blend elements still present",
      "Lower probiotic count than premium competitors",
    ],
  },
  {
    id: "greens-garden-of-life-perfect-food",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Perfect Food Raw Organic Greens",
    brand: "Garden of Life",
    grade: "A",
    pricePerServing: 0.99,
    thirdPartyTested: true,
    purityScore: 88,
    certifications: ["USDA Organic", "NSF Certified for Sport", "Non-GMO Project Verified", "Certified Vegan"],
    analysis:
      "Garden of Life leads the category in ingredient quality and certification breadth. Raw fermented greens, 34 raw organically grown ingredients, and NSF Certified for Sport for tested-athlete use. The fermentation process improves bioavailability of the nutrient compounds — a legitimate advantage over non-fermented greens powders.",
    pros: [
      "Raw fermentation process — improved nutrient bioavailability",
      "NSF Certified for Sport — trusted by competitive athletes",
      "34 raw organic ingredients with no synthetic additives",
      "Strong probiotic count (1 billion CFU) included",
    ],
    cons: [
      "Fermented taste profile is an acquired taste",
      "Dense ingredient list still hides individual amounts for some compounds",
    ],
  },
  {
    id: "greens-beam-be-amazing",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Be Amazing Greens",
    brand: "Beam",
    grade: "C",
    pricePerServing: 1.89,
    thirdPartyTested: true,
    purityScore: 71,
    certifications: ["Informed Sport"],
    analysis:
      "Beam leans heavily on lifestyle marketing and premium packaging. The formula has valid inclusions — KSM-66 ashwagandha, lion's mane mushroom, and spirulina — but dosing is masked behind blends, and at $1.89 per serving the value proposition collapses compared to sourcing those ingredients individually at verified clinical doses.",
    pros: [
      "KSM-66 ashwagandha and lion's mane are legitimately studied inclusions",
      "Informed Sport certified",
      "Well-tolerated taste profile",
    ],
    cons: [
      "Heavily blend-dependent — no way to verify individual ingredient doses",
      "Premium price doesn't reflect premium dosing transparency",
      "Mushroom content almost certainly below functional doses",
    ],
  },
  {
    id: "greens-bloom-nutrition",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Greens & Superfoods",
    brand: "Bloom Nutrition",
    grade: "D",
    pricePerServing: 1.25,
    thirdPartyTested: false,
    purityScore: 45,
    certifications: [],
    analysis:
      "A social-media-driven product with no third-party testing, heavy reliance on proprietary blends, and ingredient amounts that are almost certainly decorative for most actives. The digestive enzyme and probiotic count is unverifiably low. No certification, no purity transparency, and a price point that should come with both.",
    pros: [
      "Wide flavor variety and smooth mixability",
      "Popular flavor profiles suited to non-greens consumers",
    ],
    cons: [
      "No third-party testing or purity certification",
      "Ingredient amounts hidden behind multiple proprietary blends",
      "Probiotic and enzyme doses almost certainly below functional levels",
    ],
  },
  {
    id: "greens-naked-greens",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Naked Greens",
    brand: "Naked Nutrition",
    grade: "A",
    pricePerServing: 0.89,
    thirdPartyTested: true,
    purityScore: 89,
    certifications: ["Informed Sport", "Non-GMO Project Verified"],
    analysis:
      "The label philosophy matches the brand name. Eleven ingredients, all listed individually, no proprietary blends. Spirulina, chlorella, wheatgrass, and alfalfa at disclosed gram amounts. You may disagree with the dose sizes but you can actually see them — which disqualifies most of the competition. Best-in-class transparency for a greens product.",
    pros: [
      "No proprietary blends — all ingredient amounts fully disclosed",
      "Eleven ingredients only: no label padding with fairy-dust inclusions",
      "Informed Sport certified at a competitive price",
    ],
    cons: [
      "No probiotics or digestive enzymes — narrower functional scope",
      "Unflavored version is aggressively grassy — challenging to drink plain",
    ],
  },
  {
    id: "greens-raw-organic-perfect",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Athletic Greens Ultra Premium",
    brand: "Primal Blueprint",
    grade: "B",
    pricePerServing: 1.50,
    thirdPartyTested: true,
    purityScore: 82,
    certifications: ["USDA Organic", "Informed Sport"],
    analysis:
      "A solid mid-tier greens powder targeting ancestral nutrition principles. USDA Organic, Informed Sport certified, and probiotic-forward at 3.5 billion CFU. Still uses proprietary blend structures for some components, but the quality of individual inclusions is higher than most in the price range.",
    pros: [
      "Strong 3.5 billion CFU probiotic count",
      "USDA Organic and Informed Sport certified",
      "Quality greens sourcing with minimal processing",
    ],
    cons: [
      "Some proprietary blend elements limit full dosing transparency",
      "Higher cost than Amazing Grass for comparable organic certification",
    ],
  },
  {
    id: "greens-vega-sport-premium",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Sport Premium Protein + Greens",
    brand: "Vega",
    grade: "B",
    pricePerServing: 1.85,
    thirdPartyTested: true,
    purityScore: 83,
    certifications: ["NSF Certified for Sport", "Certified Vegan"],
    analysis:
      "Combines plant protein (pea + pumpkin seed) with a greens blend in a single product — a practical consolidation for plant-based athletes. NSF Certified for Sport is the correct standard for this use case. The greens component is secondary to the protein payload, so if you want a dedicated greens formula, look elsewhere; but as a protein+greens hybrid it delivers.",
    pros: [
      "Protein + greens in one product — reduces supplement stack complexity",
      "NSF Certified for Sport — vetted for competitive athletes",
      "Fully plant-based with complete amino acid profile",
    ],
    cons: [
      "Greens content is diluted by the protein payload — not a greens-first formula",
      "Proprietary 'tart cherry' and greens blend amounts undisclosed",
    ],
  },
  {
    id: "greens-itworks-greens",
    category: "Greens Powders",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "Greens Chews",
    brand: "It Works",
    grade: "D",
    pricePerServing: 1.60,
    thirdPartyTested: false,
    purityScore: 33,
    certifications: [],
    analysis:
      "A multi-level marketing greens product with no third-party testing and ingredient amounts so small they could only serve as label decoration. The marketing claims are aggressive; the formula is not. At $1.60 per chew you're funding a distribution pyramid, not a supplement.",
    pros: [
      "Convenient chewable format",
      "Wide flavour availability",
    ],
    cons: [
      "MLM distribution model inflates price substantially",
      "No third-party testing or purity certification",
      "Active ingredient amounts almost certainly at label-decoration levels",
    ],
  },

  // ───────── ELECTROLYTES ─────────
  {
    id: "electrolyte-lmnt",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "LMNT Recharge",
    brand: "LMNT",
    grade: "S",
    pricePerServing: 1.50,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["Informed Sport"],
    analysis:
      "LMNT is built around actual sports science: 1000mg sodium, 200mg potassium, 60mg magnesium, zero sugar, zero artificial additives. That 1000mg sodium number scares people raised on low-sodium dogma, but sweat sodium losses in hard training are substantial — and every ingredient here is disclosed at a physiologically meaningful dose. Informed Sport certified. The gold standard for athletic electrolyte replacement.",
    pros: [
      "1000mg sodium per packet — matches actual sweat losses in hard training",
      "Zero sugar, zero artificial sweeteners, zero unnecessary additives",
      "Full label transparency — every ingredient and its dose is disclosed",
      "Informed Sport certified for competitive use",
    ],
    cons: [
      "High sodium dose is intentional but may not suit low-activity users",
      "Among the pricier per-serving electrolyte options",
      "No carbohydrate content — not suited for endurance fueling alone",
    ],
  },
  {
    id: "electrolyte-precision-hydration",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "PH 1000 Electrolyte Tablet",
    brand: "Precision Hydration",
    grade: "A+",
    pricePerServing: 0.95,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["Informed Sport"],
    analysis:
      "Created by sports scientists for endurance athletes, Precision Hydration offers tiered sodium concentrations (250/500/1000/1500mg) so you can match intake to actual sweat rate — a sophisticated approach that respects individual physiology. Clean label, effective sodium-driven formula, and the science team publishes their rationale in peer-reviewed journals.",
    pros: [
      "Multiple sodium concentration tiers to match individual sweat rate",
      "Science team publishes peer-reviewed research backing the formulas",
      "Zero sugar with clean additive profile",
      "Informed Sport certified",
    ],
    cons: [
      "Requires some self-testing to determine correct sodium tier",
      "Tablet format is less convenient to mix than stick packs",
    ],
  },
  {
    id: "electrolyte-nuun-sport",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Sport Electrolyte Tablets",
    brand: "Nuun",
    grade: "A",
    pricePerServing: 0.68,
    thirdPartyTested: true,
    purityScore: 90,
    certifications: ["Informed Sport", "NSF Certified for Sport"],
    analysis:
      "A thoughtfully formulated electrolyte tablet with a mild 300mg sodium dose — lower than LMNT but appropriate for moderate activity and everyday hydration. Double-certified for competitive use, effervescent format aids rapid dissolution, and the ingredient list is clean. The go-to recommendation for recreational athletes or lower-intensity training days.",
    pros: [
      "Dual certification: Informed Sport and NSF Certified for Sport",
      "Moderate sodium dose suits recreational to intermediate training",
      "Effervescent tablet dissolves fast without shaking",
      "Clean label — no artificial colors or synthetic preservatives",
    ],
    cons: [
      "300mg sodium may be insufficient for heavy sweaters or hot-climate training",
      "Stevia sweetener has mild aftertaste for some users",
    ],
  },
  {
    id: "electrolyte-liquid-iv",
    category: "Electrolytes",
    evidenceTier: "contested",
    lastVerified: "2026-06-08",
    name: "Hydration Multiplier",
    brand: "Liquid I.V.",
    grade: "C",
    pricePerServing: 1.49,
    thirdPartyTested: false,
    purityScore: 58,
    certifications: [],
    analysis:
      "Liquid I.V. markets a 'Cellular Transport Technology' mechanism that sounds impressive but describes standard glucose-sodium co-transport — a well-established physiology principle that plain sports drinks also leverage. The formula has 11g of sugar per packet, no third-party testing certification, and costs $1.49 per stick. For hangover recovery it's fine. For athletic training, there are better options.",
    pros: [
      "Glucose-sodium co-transport mechanism does improve hydration rate",
      "Pleasant, widely available flavors",
      "Higher potassium content than some competitors",
    ],
    cons: [
      "11g sugar per packet — unnecessary for training and counterproductive for weight management",
      "No third-party testing certification at a premium price",
      "CTT marketing obscures a well-understood basic mechanism",
    ],
  },
  {
    id: "electrolyte-drip-drop",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "DripDrop ORS",
    brand: "DripDrop",
    grade: "B",
    pricePerServing: 1.35,
    thirdPartyTested: false,
    purityScore: 75,
    certifications: [],
    analysis:
      "Originally designed for clinical dehydration in disaster relief contexts — that's a meaningful origin. WHO Oral Rehydration Salt standard-aligned formula with glucose-driven sodium absorption. Higher sodium content (330mg) than standard sports drinks. Lacks third-party testing certification but the clinical backing is legitimate.",
    pros: [
      "Clinically derived formula aligned with WHO ORS standards",
      "Higher sodium content than consumer electrolyte products",
      "Glucose facilitates active sodium absorption",
    ],
    cons: [
      "No Informed Sport or equivalent testing certification",
      "Sugar content (7g) may be unwanted for keto or low-carb athletes",
    ],
  },
  {
    id: "electrolyte-ultima-replenisher",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Ultima Replenisher",
    brand: "Ultima",
    grade: "A",
    pricePerServing: 0.75,
    thirdPartyTested: true,
    purityScore: 88,
    certifications: ["Informed Sport"],
    analysis:
      "Zero sugar, naturally flavored with stevia, and covers all six electrolytes including chloride and phosphorus — broader coverage than most competitors. Informed Sport certified, clean additive profile, and a price point that makes daily use realistic. The 55mg sodium dose per serving is conservative — better for casual hydration than heavy training days.",
    pros: [
      "Full six-electrolyte spectrum including chloride and phosphorus",
      "Zero sugar with natural stevia sweetening — no artificial additives",
      "Informed Sport certified at a competitive price",
    ],
    cons: [
      "Low 55mg sodium dose — insufficient for high-sweat-rate athletic use",
      "Better suited for general hydration than intense training replacement",
    ],
  },
  {
    id: "electrolyte-powerade-zero",
    category: "Electrolytes",
    evidenceTier: "contested",
    lastVerified: "2026-06-08",
    name: "Powerade Zero",
    brand: "Coca-Cola",
    grade: "D",
    pricePerServing: 0.40,
    thirdPartyTested: false,
    purityScore: 42,
    certifications: [],
    analysis:
      "The label says electrolytes. The ingredient list says sucralose, acesulfame potassium, sodium (35mg — a fraction of sweat replacement needs), and artificial Blue 1 dye. This is a flavored water with marketing claims. The electrolyte content is too low to meaningfully impact hydration, and the artificial sweetener and dye combination lands two separate flags.",
    pros: [
      "Cheap and universally available",
      "Zero sugar for calorie-conscious users",
    ],
    cons: [
      "35mg sodium per bottle — too low for any meaningful electrolyte replacement",
      "Contains acesulfame potassium and sucralose plus Blue 1 artificial dye",
      "Marketing claims materially outpace the actual electrolyte content",
    ],
  },
  {
    id: "electrolyte-gnarly-hydrate",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Hydrate",
    brand: "Gnarly Nutrition",
    grade: "A+",
    pricePerServing: 0.85,
    thirdPartyTested: true,
    purityScore: 93,
    certifications: ["Informed Sport", "NSF Certified for Sport"],
    analysis:
      "Built for endurance athletes by a brand that sponsors actual pro athletes — the formula reflects that. 460mg sodium, complete electrolyte profile, naturally sweetened, double-certified. No proprietary blends, no artificial additives, and priced competitively for a dual-certified product. One of the most underrated electrolyte products in the category.",
    pros: [
      "460mg sodium — appropriate for moderate-to-high intensity training",
      "Dual certified: Informed Sport and NSF Certified for Sport",
      "Natural sweetening with no artificial dyes or flavors",
      "Full label transparency on all ingredients",
    ],
    cons: [
      "Less mainstream visibility than Nuun or LMNT — harder to find in Canadian retail",
      "Mild flavor intensity compared to sweeter competitors",
    ],
  },
  {
    id: "electrolyte-hydrant-rapid-hydration",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Rapid Hydration Mix",
    brand: "Hydrant",
    grade: "B",
    pricePerServing: 1.10,
    thirdPartyTested: false,
    purityScore: 74,
    certifications: [],
    analysis:
      "A glucose-sodium co-transport formula with a clean-ish ingredient list. The 144mg sodium is on the lower end but the glucose-driven absorption mechanism makes it physiologically effective beyond what the number suggests. No third-party certification at this price is a flag — you're trusting label accuracy without verification.",
    pros: [
      "Glucose-sodium co-transport formula improves water absorption rate",
      "Relatively clean additive profile",
      "Convenient stick pack format",
    ],
    cons: [
      "No Informed Sport or NSF certification at $1.10/serving",
      "Lower sodium content limits utility for heavy athletic training",
    ],
  },

  // ───────── COLLAGEN ─────────
  {
    id: "collagen-vital-proteins-marine",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Marine Collagen",
    brand: "Vital Proteins",
    grade: "S",
    pricePerServing: 0.85,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["NSF Certified for Sport", "Wild-Caught Certified"],
    analysis:
      "Marine collagen has the highest bioavailability of any collagen type due to its smaller peptide size. Vital Proteins sources from wild-caught fish — not farmed — which limits heavy metal bioaccumulation exposure. NSF Certified for Sport, single-ingredient label, and 10g collagen peptides per serving at the clinically studied dose range. The benchmark in this category.",
    pros: [
      "Marine source — highest bioavailability of all collagen types",
      "Wild-caught certified — minimizes heavy metal exposure from farmed sources",
      "NSF Certified for Sport — independently verified purity and safety",
      "Clean single-ingredient label with no unnecessary additives",
    ],
    cons: [
      "Not suitable for vegans or those with fish allergies",
      "Some users find the marine scent noticeable when mixed in water",
    ],
  },
  {
    id: "collagen-momentous-bovine",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Collagen Peptides",
    brand: "Momentous",
    grade: "A+",
    pricePerServing: 1.10,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["NSF Certified for Sport", "Informed Sport"],
    analysis:
      "Momentous formulates around athlete performance and the collagen is no different — grass-fed bovine Type I and III at 10g per serving with vitamin C co-formulation to support collagen synthesis. The vitamin C pairing is specifically what the research supports: collagen + vitamin C pre-workout or pre-sleep for tendon and ligament repair. Double-certified and well-formulated.",
    pros: [
      "Vitamin C co-formulation supports collagen synthesis — not just filler",
      "Dual certified: NSF Certified for Sport and Informed Sport",
      "Grass-fed bovine sourcing with full traceability",
      "10g collagen peptides at the clinically studied dose range",
    ],
    cons: [
      "Premium pricing — among the most expensive collagen per gram",
      "Bovine-sourced — not suitable for pescatarians or vegans",
    ],
  },
  {
    id: "collagen-sports-research-bovine",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Collagen Peptides Powder",
    brand: "Sports Research",
    grade: "A+",
    pricePerServing: 0.55,
    thirdPartyTested: true,
    purityScore: 95,
    certifications: ["Informed Sport", "Certified Paleo", "Non-GMO Project Verified"],
    analysis:
      "Best value in the collagen category. Hydrolyzed Type I and III from pasture-raised bovine, Informed Sport certified, and priced at roughly half of premium competitors for equivalent collagen peptide content. Third-party lab results are published on their website. Mixes odorlessly into hot or cold liquids — high compliance product.",
    pros: [
      "Best price-per-gram of collagen peptides in this roundup",
      "Informed Sport certified at a budget-accessible price",
      "Pasture-raised bovine sourcing with published lab results",
      "Odorless, tasteless — mixes into anything",
    ],
    cons: [
      "No vitamin C co-formulation — must supplement separately for optimal synthesis",
      "Bovine-only sourcing — no marine or multi-source option",
    ],
  },
  {
    id: "collagen-garden-of-life-grass-fed",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Grass Fed Collagen Beauty",
    brand: "Garden of Life",
    grade: "A",
    pricePerServing: 1.05,
    thirdPartyTested: true,
    purityScore: 90,
    certifications: ["NSF Certified for Sport", "Certified Paleo", "Certified Grass Fed"],
    analysis:
      "NSF Certified for Sport with grass-fed certification and added biotin, vitamin C, and silica for comprehensive skin, hair, and connective tissue support. The addition of these synergistic nutrients is evidence-informed rather than purely cosmetic — biotin and vitamin C are genuine cofactors for collagen and keratin synthesis.",
    pros: [
      "Synergistic formula: collagen + vitamin C + biotin + silica",
      "NSF Certified for Sport and Certified Grass Fed",
      "Comprehensive connective tissue support beyond just collagen",
    ],
    cons: [
      "Beauty-positioned marketing may undersell its athletic recovery utility",
      "Higher cost per gram of collagen than Sports Research equivalent",
    ],
  },
  {
    id: "collagen-further-food-premium",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Premium Marine Collagen",
    brand: "Further Food",
    grade: "A",
    pricePerServing: 0.95,
    thirdPartyTested: true,
    purityScore: 91,
    certifications: ["Informed Sport", "Wild-Caught Certified", "Non-GMO Project Verified"],
    analysis:
      "Further Food's marine collagen comes with third-party heavy metal testing documentation — a relevant concern given marine source contamination risks. Informed Sport certified, wild-caught, and 10g per serving. A solid marine alternative to the Vital Proteins benchmark, slightly more affordable and with comparable certification depth.",
    pros: [
      "Published heavy metal testing documentation — critical for marine sources",
      "Wild-caught certified with Informed Sport verification",
      "10g marine collagen peptides at competitive price",
    ],
    cons: [
      "Slight marine scent in some flavor variants",
      "Not NSF Certified for Sport — Informed Sport only",
    ],
  },
  {
    id: "collagen-neocell-super",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Super Collagen Type 1&3",
    brand: "NeoCell",
    grade: "B",
    pricePerServing: 0.38,
    thirdPartyTested: true,
    purityScore: 82,
    certifications: ["NSF Certified"],
    analysis:
      "A broadly available, affordable bovine collagen with NSF Certified (not for Sport — basic NSF) status. Higher tablet count per serving is a minor inconvenience, and the collagen dose per serving (6g) is slightly below the 10g cited in most sports performance studies. Functional product at a budget price, but athletes pushing tissue repair would benefit from a higher-dose option.",
    pros: [
      "Budget-friendly with NSF Certified manufacturing verification",
      "Type 1 and 3 collagen widely available at pharmacies",
      "Established brand with decades of production history",
    ],
    cons: [
      "6g collagen dose — below the 10g used in most positive clinical studies",
      "NSF Certified (not for Sport) — less rigorous than NSF Certified for Sport",
      "Tablet format requires high pill count per serving",
    ],
  },
  {
    id: "collagen-vital-proteins-original",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Collagen Peptides",
    brand: "Vital Proteins",
    grade: "A+",
    pricePerServing: 0.70,
    thirdPartyTested: true,
    purityScore: 94,
    certifications: ["Informed Sport", "Certified Grass Fed", "Non-GMO Project Verified"],
    analysis:
      "The original that launched the collagen category. Pasture-raised bovine peptides, Informed Sport certified, and formulated at the 20g serving size that falls within the higher end of clinical study doses. The hyaluronic acid addition has legitimate emerging research for joint lubrication. A consistently excellent product despite the category's proliferation.",
    pros: [
      "20g collagen per serving — higher end of clinically studied doses",
      "Hyaluronic acid co-formulation supports joint health",
      "Certified grass-fed with Informed Sport verification",
    ],
    cons: [
      "Among the pricier bovine collagen options at full 20g dose",
      "Hyaluronic acid dose could be higher for optimal joint effect",
    ],
  },
  {
    id: "collagen-schiff-move-free",
    category: "Collagen",
    evidenceTier: "contested",
    lastVerified: "2026-06-08",
    name: "Move Free Ultra Collagen",
    brand: "Schiff",
    grade: "C",
    pricePerServing: 0.65,
    thirdPartyTested: false,
    purityScore: 60,
    certifications: [],
    analysis:
      "Blends collagen with glucosamine and chondroitin, which sounds comprehensive but hides the fact that each individual ingredient is underdosed relative to studied amounts. No third-party testing despite a mid-range price point. The joint health space is full of underdosed multi-ingredient products like this one — you're better off with a higher-dose collagen plus targeted single ingredients.",
    pros: [
      "Combines collagen, glucosamine, and chondroitin in one product",
      "Available at most Canadian pharmacies",
    ],
    cons: [
      "Each ingredient likely underdosed below studied effective amounts",
      "No third-party purity or potency verification",
      "Glucosamine and chondroitin joint research has become increasingly contested",
    ],
  },

  // ───────── VITAMINS & MINERALS ─────────
  {
    id: "vitamins-thorne-basic-nutrients",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Basic Nutrients 2/Day",
    brand: "Thorne Research",
    grade: "S",
    pricePerServing: 0.65,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["NSF Certified for Sport"],
    analysis:
      "The gold standard multi-vitamin for athletes. Thorne uses methylated B-vitamin forms (methylfolate, methylcobalamin) that are bioavailable regardless of MTHFR gene variants, chelated mineral forms with superior absorption, and no fillers, dyes, or excipients that compromise purity. NSF Certified for Sport. Two capsules per day at a price that beats every competitor at equivalent quality.",
    pros: [
      "Methylated B-vitamins — bioavailable for all MTHFR gene variants",
      "Chelated minerals for superior absorption over oxide forms",
      "NSF Certified for Sport — pharmaceutical-grade manufacturing",
      "Zero fillers, dyes, or artificial excipients",
    ],
    cons: [
      "2-capsule daily requirement (not single-pill convenience)",
      "No iron included — may require separate supplementation for some users",
    ],
  },
  {
    id: "vitamins-pure-encapsulations-one",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "ONE Multivitamin",
    brand: "Pure Encapsulations",
    grade: "S",
    pricePerServing: 0.75,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["NSF Certified", "Informed Sport"],
    analysis:
      "Pure Encapsulations built its reputation on hypoallergenic, additive-free formulations — and ONE exemplifies that. No wheat, gluten, eggs, peanuts, magnesium stearate, hydrogenated oils, or artificial sweeteners in any product. All vitamin forms are bioavailable (not cheapest-available), and the manufacturing quality is consistently pharmaceutical-standard. The best hypoallergenic multi on the market.",
    pros: [
      "Hypoallergenic: free from the major food allergens and manufacturing additives",
      "Bioavailable vitamin forms throughout — no cheap oxide or cyanocobalamin shortcuts",
      "NSF Certified manufacturing with Informed Sport verification",
    ],
    cons: [
      "Among the priciest multivitamins per serving",
      "Capsule-only format with no chewable or gummy option",
    ],
  },
  {
    id: "vitamins-athletic-pure-pack",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Athletic Pure Pack",
    brand: "Pure Encapsulations",
    grade: "A+",
    pricePerServing: 1.85,
    thirdPartyTested: true,
    purityScore: 97,
    certifications: ["NSF Certified", "Informed Sport"],
    analysis:
      "An athlete-specific multi that goes beyond a standard vitamin formula — adds EPA/DHA omega-3 (from fish oil), CoQ10, and vitamin D3 in a single daily packet. Eliminates the need for separate fish oil supplementation for users with moderate omega-3 needs. NSF Certified, hypoallergenic, and comprehensively formulated for active individuals.",
    pros: [
      "Athlete-specific formula includes fish oil, CoQ10, and D3",
      "Eliminates need for separate omega-3 supplementation",
      "NSF Certified with hypoallergenic Pure Encapsulations standards",
    ],
    cons: [
      "Expensive at $1.85/packet — covers multiple supplements but cost adds up",
      "Omega-3 dose (400mg EPA+DHA) is below what most athletes need independently",
    ],
  },
  {
    id: "vitamins-megafood-men-one-daily",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Men's One Daily Multi",
    brand: "MegaFood",
    grade: "A",
    pricePerServing: 0.52,
    thirdPartyTested: true,
    purityScore: 91,
    certifications: ["NSF Certified", "Non-GMO Project Verified", "Certified B Corp", "USDA Organic"],
    analysis:
      "Food-matrix fermentation process binds nutrients to whole-food complexes, improving bioavailability without synthetic isolates. USDA Organic, B Corp certified, and NSF verified. The men's formula appropriately excludes iron (often excessive for men) and includes saw palmetto. Solid values-aligned product for the organic-conscious athlete.",
    pros: [
      "Whole-food matrix delivery — improved bioavailability vs. synthetic isolates",
      "USDA Organic, NSF Certified, and B Corp certified",
      "Men's formula appropriately excludes iron",
    ],
    cons: [
      "Food-based delivery means lower potency for some micronutrients vs. isolated forms",
      "Single capsule may not cover all micronutrients at full therapeutic doses",
    ],
  },
  {
    id: "vitamins-vitamin-d3-k2-thorne",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Vitamin D3 + K2",
    brand: "Thorne Research",
    grade: "S",
    pricePerServing: 0.22,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["NSF Certified for Sport"],
    analysis:
      "Vitamin D3 deficiency is near-universal in northern climates — if you live in Canada, you're almost certainly not getting enough year-round. The K2 pairing (MK-7 form) is critical: D3 without K2 can dysregulate calcium deposition, directing it toward soft tissues rather than bone. Thorne's D3+K2 uses the bioactive MK-7 form at proven doses. NSF Certified for Sport. One of the highest-impact, lowest-cost interventions available.",
    pros: [
      "D3 + MK-7 K2 pairing prevents D3-driven calcium dysregulation",
      "Vitamin D deficiency is extremely common in Canada — high relevance",
      "NSF Certified for Sport at extremely low cost per day",
      "Liquid drop format allows precise dose titration",
    ],
    cons: [
      "Liquid drop format requires refrigeration after opening",
      "Does not replace a full multivitamin for broader micronutrient needs",
    ],
  },
  {
    id: "vitamins-magnesium-glycinate-doctors-best",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "High Absorption Magnesium",
    brand: "Doctor's Best",
    grade: "A+",
    pricePerServing: 0.18,
    thirdPartyTested: true,
    purityScore: 95,
    certifications: ["Informed Sport"],
    analysis:
      "TRAACS chelated magnesium glycinate — one of the most bioavailable mineral forms available, independently verified, and priced at $0.18 per serving. Athletes consuming magnesium oxide from cheaper competitors are getting half the elemental absorption for similar cost. This is the correct magnesium form, at the correct dose, at the lowest sensible price.",
    pros: [
      "TRAACS chelated glycinate — highest-bioavailability magnesium form",
      "Informed Sport certified at an exceptional value price",
      "Large capsule supply per bottle reduces cost per month",
    ],
    cons: [
      "Capsule size is large — some users find it difficult to swallow",
      "Standalone mineral — no co-factors or vitamin pairing",
    ],
  },
  {
    id: "vitamins-zinc-copper-thorne",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Zinc Bisglycinate",
    brand: "Thorne Research",
    grade: "S",
    pricePerServing: 0.20,
    thirdPartyTested: true,
    purityScore: 99,
    certifications: ["NSF Certified for Sport"],
    analysis:
      "Zinc status directly regulates testosterone production, immune function, and protein synthesis — three things every athlete cares about. The bisglycinate chelate achieves near-complete absorption without the GI distress of zinc sulfate or oxide forms. NSF Certified for Sport. One capsule delivers 15mg elemental zinc — enough to restore deficiency without the copper imbalance risk of high-dose zinc supplements.",
    pros: [
      "Bisglycinate chelate — superior absorption without GI side effects",
      "15mg dose appropriate for deficiency correction without copper depletion",
      "NSF Certified for Sport — safe for all competitive levels",
    ],
    cons: [
      "Standalone zinc — users with low copper should add copper supplementation",
      "No co-factors included; pairs best with a complete multivitamin",
    ],
  },
  {
    id: "vitamins-iron-ferrochel",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Ferrochel Iron Bisglycinate",
    brand: "Thorne Research",
    grade: "A+",
    pricePerServing: 0.28,
    thirdPartyTested: true,
    purityScore: 98,
    certifications: ["NSF Certified for Sport"],
    analysis:
      "Iron deficiency is the most common nutritional deficiency in female athletes and affects endurance performance directly. The bisglycinate form (Ferrochel) causes dramatically less GI distress than ferrous sulfate — the standard form in most pharmacy iron supplements. NSF Certified for Sport. Only supplement if blood work confirms deficiency; excess iron is harmful.",
    pros: [
      "Ferrochel bisglycinate — 2x iron absorption with 60% less GI distress vs. sulfate",
      "NSF Certified for Sport — verified safe for athletes",
      "Appropriate for addressing confirmed iron deficiency",
    ],
    cons: [
      "Should not be supplemented without confirmed blood work deficiency",
      "Not appropriate for most men without medical indication",
    ],
  },
  {
    id: "vitamins-vitamin-c-quercetin",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Vitamin C with Quercetin",
    brand: "Pure Encapsulations",
    grade: "A",
    pricePerServing: 0.45,
    thirdPartyTested: true,
    purityScore: 96,
    certifications: ["NSF Certified"],
    analysis:
      "Vitamin C at 1000mg paired with quercetin — a flavonoid that regenerates ascorbic acid in vivo and provides independent antioxidant and anti-inflammatory signaling. Relevant for athletes for collagen synthesis (pre-workout dosing), immune function, and post-exercise recovery. Pure Encapsulations' additive-free formulation is the correct delivery vehicle for this combination.",
    pros: [
      "Quercetin + Vitamin C pairing enhances in-vivo ascorbic acid recycling",
      "1000mg Vitamin C — meaningful dose for collagen synthesis and immune support",
      "NSF Certified, hypoallergenic, no unnecessary additives",
    ],
    cons: [
      "Time-release format is better absorbed than single large doses — this product is standard release",
      "Quercetin dose (500mg) at the lower end of studied anti-inflammatory amounts",
    ],
  },
  {
    id: "vitamins-centrum-silver",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Centrum Silver Adults 50+",
    brand: "Centrum",
    grade: "D",
    pricePerServing: 0.08,
    thirdPartyTested: false,
    purityScore: 45,
    certifications: [],
    analysis:
      "The default multi that doctors recommend because it's familiar and cheap — not because it's good. Cyanocobalamin instead of methylcobalamin, magnesium oxide (poorly absorbed), folic acid instead of methylfolate, synthetic vitamin E (dl-alpha-tocopherol — half as bioavailable as natural), and multiple artificial colors and additives. At $0.08 per tablet the price makes sense; the nutrient forms do not.",
    pros: [
      "Extremely cheap and universally available at pharmacies",
      "USP Verified for basic label accuracy",
    ],
    cons: [
      "Inferior nutrient forms throughout: oxide minerals, cyanocobalamin, synthetic vitamin E",
      "Artificial colors (Red 40, Yellow 6) — unnecessary in a supplement",
      "No third-party athletic testing certification",
    ],
  },
  {
    id: "vitamins-one-a-day-gummy",
    category: "Vitamins & Minerals",
    evidenceTier: "precautionary",
    lastVerified: "2026-06-08",
    name: "One A Day Vitacraves Gummies",
    brand: "Bayer",
    grade: "D",
    pricePerServing: 0.18,
    thirdPartyTested: false,
    purityScore: 35,
    certifications: [],
    analysis:
      "Sugar, glucose syrup, gelatin, and artificial colors — then vitamins. The vitamin doses are well below the amounts used in research, the forms are the cheapest available, and gummy supplement potency is notoriously unreliable: sugar interferes with accurate vitamin dosing during manufacturing and the gummies lose potency faster than capsules. This is candy with vitamin claims.",
    pros: [
      "Easy to take — no swallowing capsules",
      "Widely available and inexpensive",
    ],
    cons: [
      "3g of sugar per serving — adds up at the daily dose",
      "Gummy format has documented potency accuracy issues",
      "Cheapest possible vitamin forms — minimal bioavailability",
    ],
  },
  {
    id: "vitamins-bio-tech-d3-50000",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "D3 5000 IU",
    brand: "Bio-Tech Pharmacal",
    grade: "A",
    pricePerServing: 0.08,
    thirdPartyTested: true,
    purityScore: 90,
    certifications: ["USP Verified"],
    analysis:
      "5000 IU D3 per capsule for individuals with confirmed deficiency or geographic risk (northern latitudes, minimal sun exposure). USP Verified for potency accuracy. Dirt cheap per dose, single ingredient, no additives. The 5000 IU dose requires periodic 25(OH)D blood monitoring — this is a higher therapeutic dose, not a maintenance product for everyone.",
    pros: [
      "5000 IU — appropriate for correcting confirmed deficiency",
      "USP Verified potency accuracy at extremely low cost",
      "Single ingredient, no additives or fillers",
    ],
    cons: [
      "High dose requires blood monitoring — not a general-population maintenance product",
      "USP Certified (not for Sport) — athletes need Thorne or equivalent for NSF",
    ],
  },
  {
    id: "vitamins-klean-athlete-b-complex",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "B-Complex",
    brand: "Klean Athlete",
    grade: "A+",
    pricePerServing: 0.30,
    thirdPartyTested: true,
    purityScore: 96,
    certifications: ["NSF Certified for Sport"],
    analysis:
      "B-vitamins are central to energy metabolism, red blood cell production, and neurological function — particularly relevant for athletes in heavy training blocks. Klean Athlete's B-Complex uses active folate and methylcobalamin (not the cheaper folic acid and cyanocobalamin), covers all eight B-vitamins at meaningful doses, and is NSF Certified for Sport. Clean, comprehensive, and correctly formulated.",
    pros: [
      "Active B-vitamin forms throughout — methylfolate, methylcobalamin, P5P",
      "NSF Certified for Sport — safe for competitive athletes",
      "Complete 8-vitamin B-complex coverage at therapeutic doses",
    ],
    cons: [
      "Must be taken with food — empty-stomach dosing causes nausea in some users",
      "Urine turns fluorescent yellow — normal but alarming to first-time users",
    ],
  },
  {
    id: "vitamins-nordic-naturals-omega-d3",
    category: "Vitamins & Minerals",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Omega-3 + D3 Gummy",
    brand: "Nordic Naturals",
    grade: "B",
    pricePerServing: 0.72,
    thirdPartyTested: true,
    purityScore: 84,
    certifications: ["IFOS Certified", "NSF Certified"],
    analysis:
      "Combines verified omega-3 with vitamin D3 in a gummy format — a useful pairing for compliance-challenged users. Nordic Naturals' IFOS certification guarantees fish oil quality and the D3 dose (1000 IU) is appropriate for daily maintenance rather than deficiency correction. The gummy format adds a small amount of sugar and pectin but avoids the artificial colors of cheaper gummy supplements.",
    pros: [
      "Omega-3 + D3 pairing in a convenient, compliance-friendly gummy",
      "IFOS certified fish oil — highest industry standard",
      "No artificial colors or flavors in the gummy format",
    ],
    cons: [
      "2g sugar per serving — small but adds up with daily use",
      "1000 IU D3 is maintenance-level — insufficient for deficiency correction",
    ],
  },

  // ── additional Collagen ──
  {
    id: "collagen-bulletproof-unflavored",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Unflavored Collagen Protein",
    brand: "Bulletproof",
    grade: "A",
    pricePerServing: 0.90,
    thirdPartyTested: true,
    purityScore: 92,
    certifications: ["Informed Sport", "Certified Grass Fed"],
    analysis:
      "Grass-fed bovine collagen peptides at 18g per serving with Informed Sport certification. Bulletproof leans into a high-fat, performance-nutrition identity and the collagen fits that philosophy — quick dissolving, unflavored, and stacks easily into coffee or smoothies without changing texture. Solid product that earns its premium positioning without resorting to proprietary blend obscuration.",
    pros: [
      "18g collagen per serving — high dose within clinically studied range",
      "Informed Sport certified, grass-fed sourced",
      "Unflavored and dissolves invisibly in hot or cold liquids",
    ],
    cons: [
      "No vitamin C co-formulation — must supplement separately for optimal synthesis",
      "Bulletproof branding carries a premium that isn't fully warranted by the formulation",
    ],
  },
  {
    id: "collagen-codeage-multi-collagen",
    category: "Collagen",
    evidenceTier: "emerging-evidence",
    lastVerified: "2026-06-08",
    name: "Multi Collagen Protein",
    brand: "Codeage",
    grade: "B",
    pricePerServing: 0.80,
    thirdPartyTested: true,
    purityScore: 85,
    certifications: ["Informed Sport"],
    analysis:
      "Covers five collagen types (I, II, III, V, X) from four sources — bovine, marine, eggshell, and chicken. The type II collagen from chicken sternum is specifically associated with joint cartilage research. Informed Sport certified. The multi-source approach makes dose per individual collagen type lower, and the research on Type X and V collagen is thin — but for joint-focused users, the Type II inclusion is a legitimate addition.",
    pros: [
      "Type II chicken collagen — specifically studied for joint cartilage health",
      "Multi-source covering Types I, II, III, V, X",
      "Informed Sport certified",
    ],
    cons: [
      "Lower per-type dose due to source dilution across five collagen types",
      "Research on Types V and X is much thinner than Type I/II/III",
    ],
  },

  // ── additional Electrolyte ──
  {
    id: "electrolyte-skratch-sport-hydration",
    category: "Electrolytes",
    evidenceTier: "strong-consensus",
    lastVerified: "2026-06-08",
    name: "Sport Hydration Drink Mix",
    brand: "Skratch Labs",
    grade: "A+",
    pricePerServing: 1.30,
    thirdPartyTested: true,
    purityScore: 94,
    certifications: ["Informed Sport", "NSF Certified for Sport"],
    analysis:
      "Created by a sports physiologist for actual athletes — Skratch Labs' formulas are built around real-world sweat data, not marketing. The 380mg sodium dose falls in the evidence-backed range for moderate training, natural cane sugar provides quick carbohydrate fuel without HFCS, and there are zero artificial flavors, colors, or sweeteners. Dual-certified. The pre-workout or mid-workout electrolyte of choice for endurance athletes.",
    pros: [
      "Physiologist-designed formula built from sweat-rate research",
      "380mg sodium with real sugar — appropriate for endurance fueling",
      "Dual certified: Informed Sport and NSF Certified for Sport",
      "No artificial sweeteners, flavors, or colors",
    ],
    cons: [
      "20g carbohydrates per serving — not appropriate for keto or low-carb athletes",
      "Sugar content means this is a fueling product, not a pure hydration product",
    ],
  },
];
