/**
 * Hardcoded curated food database — common Canadian consumer products that must
 * always return a result regardless of external API availability.
 *
 * Nutrition values are per 100ml (for beverages) or per 100g (for foods).
 * These go through the normal food scoring pipeline — no special cases.
 */

import type { OffProduct } from "./openFoodFacts";
import type { Nutriments } from "./scoring";

type CuratedFoodEntry = {
  barcode: string;
  name: string;
  brand: string;
  servingSize?: string;
  categoriesTags: string[];
  ingredientsText: string;
  nutriments: Nutriments;
  novaGroup?: number;
};

// ── Per-100ml soft drink nutrition ────────────────────────────────────────────
// Standard 355ml can → divide by 3.55 for per-100ml values.

const SODAS: CuratedFoodEntry[] = [
  {
    barcode: "0062100012284",
    name: "Canada Dry Zero Sugar Ginger Ale",
    brand: "Canada Dry",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:diet-sodas"],
    ingredientsText: "Carbonated water, citric acid, natural flavours, sodium citrate, aspartame, acesulfame potassium, sodium benzoate",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0.05,
    },
  },
  {
    barcode: "0062100012291",
    name: "Canada Dry Ginger Ale",
    brand: "Canada Dry",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas"],
    ingredientsText: "Carbonated water, high fructose corn syrup, citric acid, natural flavours, sodium citrate, caramel colour, sodium benzoate",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 39,
      carbohydrates_100g: 11,
      sugars_100g: 11,
      proteins_100g: 0,
      salt_100g: 0.02,
    },
  },
  {
    barcode: "0069000019832",
    name: "Coca-Cola Classic",
    brand: "Coca-Cola",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:colas"],
    ingredientsText: "Carbonated water, high fructose corn syrup, caramel colour (class IV), phosphoric acid, natural flavours, caffeine",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 39,
      carbohydrates_100g: 11,
      sugars_100g: 11,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0069000012527",
    name: "Diet Coke",
    brand: "Coca-Cola",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:diet-sodas", "en:colas"],
    ingredientsText: "Carbonated water, caramel colour (class IV), phosphoric acid, natural flavours, citric acid, aspartame, acesulfame potassium, caffeine",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    // User-reported barcode: 069000010013 (UPC-A). Different SKU from 0069000012527.
    barcode: "069000010013",
    name: "Diet Coke",
    brand: "Coca-Cola",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:diet-sodas", "en:colas"],
    ingredientsText: "Carbonated water, caramel colour (class IV), phosphoric acid, natural flavours, citric acid, aspartame, acesulfame potassium, caffeine",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0069000010013",
    name: "Diet Coke",
    brand: "Coca-Cola",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:diet-sodas", "en:colas"],
    ingredientsText: "Carbonated water, caramel colour (class IV), phosphoric acid, natural flavours, citric acid, aspartame, acesulfame potassium, caffeine",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0069000008947",
    name: "Pepsi",
    brand: "PepsiCo",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:colas"],
    ingredientsText: "Carbonated water, high fructose corn syrup, caramel colour, phosphoric acid, caffeine, citric acid, natural flavours",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 42,
      carbohydrates_100g: 11.5,
      sugars_100g: 11.5,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0069000016534",
    name: "Diet Pepsi",
    brand: "PepsiCo",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas", "en:diet-sodas", "en:colas"],
    ingredientsText: "Carbonated water, caramel colour, phosphoric acid, citric acid, aspartame, acesulfame potassium, caffeine, natural flavours",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0069000019849",
    name: "Sprite",
    brand: "Coca-Cola",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sodas"],
    ingredientsText: "Carbonated water, high fructose corn syrup, citric acid, natural flavours, sodium citrate, sodium benzoate",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 39,
      carbohydrates_100g: 10.7,
      sugars_100g: 10.7,
      proteins_100g: 0,
      salt_100g: 0.02,
    },
  },
  {
    barcode: "0012000174834",
    name: "Bubly Sparkling Water",
    brand: "Bubly",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sparkling-waters"],
    ingredientsText: "Carbonated water, natural flavour",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0,
    },
  },
  {
    barcode: "0012000174827",
    name: "Bubly Sparkling Water",
    brand: "Bubly",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:carbonated-drinks", "en:sparkling-waters"],
    ingredientsText: "Carbonated water, natural flavour",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0,
    },
  },
  {
    barcode: "0052000004567",
    name: "Gatorade Thirst Quencher Lemon-Lime",
    brand: "Gatorade",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:sports-drinks", "en:energy-drinks"],
    ingredientsText: "Water, sucrose, dextrose, citric acid, natural flavor, sodium chloride, sodium citrate, monopotassium phosphate, modified food starch, glycerol ester of wood rosin, yellow 5, yellow 6",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 26,
      carbohydrates_100g: 6.3,
      sugars_100g: 6.3,
      proteins_100g: 0,
      salt_100g: 0.06,
    },
  },
  {
    barcode: "0052000137027",
    name: "Gatorade Thirst Quencher",
    brand: "Gatorade",
    servingSize: "355ml",
    categoriesTags: ["en:beverages", "en:sports-drinks", "en:energy-drinks"],
    ingredientsText: "Water, sucrose, dextrose, citric acid, natural flavor, sodium chloride, sodium citrate, monopotassium phosphate, modified food starch, glycerol ester of wood rosin, artificial color",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 26,
      carbohydrates_100g: 6.3,
      sugars_100g: 6.3,
      proteins_100g: 0,
      salt_100g: 0.06,
    },
  },
  {
    barcode: "0786162110013",
    name: "Vitaminwater Orange",
    brand: "vitaminwater",
    servingSize: "591ml",
    categoriesTags: ["en:beverages", "en:waters", "en:flavored-waters", "en:fortified-waters"],
    ingredientsText: "Reverse osmosis water, crystalline fructose, cane sugar, citric acid, vegetable juice (color), natural flavor, ascorbic acid (vitamin C), niacin, pantothenic acid, pyridoxine hydrochloride (B6), cyanocobalamin (B12)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 19,
      carbohydrates_100g: 5,
      sugars_100g: 5,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0786162101691",
    name: "Vitaminwater XXX",
    brand: "vitaminwater",
    servingSize: "591ml",
    categoriesTags: ["en:beverages", "en:waters", "en:flavored-waters", "en:fortified-waters"],
    ingredientsText: "Reverse osmosis water, crystalline fructose, cane sugar, citric acid, vegetable juice (color), natural flavor, ascorbic acid (vitamin C), niacin, pantothenic acid, pyridoxine hydrochloride (B6), cyanocobalamin (B12)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 19,
      carbohydrates_100g: 5,
      sugars_100g: 5,
      proteins_100g: 0,
      salt_100g: 0.01,
    },
  },
];

// ── Per-100g packaged food nutrition ─────────────────────────────────────────

const PACKAGED_FOODS: CuratedFoodEntry[] = [
  {
    barcode: "0057000021691",
    name: "Tomato Ketchup",
    brand: "Heinz",
    servingSize: "15g",
    categoriesTags: ["en:condiments", "en:sauces", "en:ketchup"],
    ingredientsText: "Tomato concentrate, distilled vinegar, high fructose corn syrup, corn syrup, salt, spice, onion powder, natural flavoring",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 133,
      carbohydrates_100g: 33,
      sugars_100g: 27,
      proteins_100g: 1.5,
      salt_100g: 2.3,
      "saturated-fat_100g": 0,
    },
  },
  {
    // Barcode corrected 2026-06: 0028400090308 is Doritos, not Lay's.
    barcode: "0028400090155",
    name: "Lay's Classic",
    brand: "Frito-Lay",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks"],
    ingredientsText: "Potatoes, vegetable oil (sunflower, corn, and/or canola oil), salt",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 54,
      sugars_100g: 0.5,
      proteins_100g: 7,
      salt_100g: 1.8,
      "saturated-fat_100g": 1.8,
    },
  },
  {
    barcode: "0028400090308",
    name: "Doritos Nacho Cheese",
    brand: "Frito-Lay",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks", "en:tortilla-chips"],
    ingredientsText: "Corn, vegetable oil, seasoning (whey, cheddar cheese, maltodextrin, salt, monosodium glutamate, artificial colours [Yellow 6, Yellow 5, Red 40], natural and artificial flavours, lactic acid, citric acid)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 60,
      sugars_100g: 2.8,
      proteins_100g: 7,
      salt_100g: 1.6,
      "saturated-fat_100g": 4,
    },
  },
  {
    barcode: "0028400590679",
    name: "Tostitos Restaurant Style",
    brand: "Frito-Lay",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks", "en:tortilla-chips"],
    ingredientsText: "Corn, vegetable oil (corn, canola, and/or sunflower oil), salt",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 68,
      sugars_100g: 0,
      proteins_100g: 7,
      salt_100g: 1.0,
      "saturated-fat_100g": 1.8,
    },
  },
  {
    barcode: "0044000030131",
    name: "Oreo Original",
    brand: "Nabisco",
    servingSize: "34g",
    categoriesTags: ["en:snacks", "en:sweet-snacks", "en:biscuits-and-cakes", "en:cookies"],
    ingredientsText: "Unbleached enriched flour, sugar, palm and/or canola oil, cocoa (processed with alkali), high fructose corn syrup, leavening, cornstarch, salt, soy lecithin, vanillin (artificial flavour)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 471,
      carbohydrates_100g: 74,
      sugars_100g: 41,
      proteins_100g: 5,
      salt_100g: 1.3,
      "saturated-fat_100g": 7.4,
    },
  },
  // ── Sauce & condiment calibration (confirmed 2026-06 vs Yuka) ──────────────
  {
    barcode: "0058300854519",
    name: "Thick 'n Chunky Salsa",
    brand: "Old El Paso",
    servingSize: "30g",
    categoriesTags: ["en:condiments", "en:sauces", "en:salsas"],
    ingredientsText: "Diced tomatoes, tomatoes, water, onions, jalapeño peppers, vinegar, salt, garlic, xanthan gum, sodium benzoate (to preserve freshness), potassium sorbate (to preserve freshness), natural flavour, paprika extract",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 33,
      carbohydrates_100g: 7,
      sugars_100g: 4,
      proteins_100g: 1,
      salt_100g: 0.88,
      "saturated-fat_100g": 0,
    },
  },
  {
    barcode: "0057000013165",
    name: "Tomato Ketchup",
    brand: "Heinz",
    servingSize: "15g",
    categoriesTags: ["en:condiments", "en:sauces", "en:ketchup"],
    ingredientsText: "Tomato concentrate, distilled vinegar, sugar, salt, onion powder, spice, natural flavouring",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 133,
      carbohydrates_100g: 33,
      sugars_100g: 27,
      proteins_100g: 1.5,
      salt_100g: 1.9,
      "saturated-fat_100g": 0,
    },
  },
  {
    barcode: "0068100903591",
    name: "Ranchers Choice Dressing",
    brand: "Kraft",
    servingSize: "30g",
    categoriesTags: ["en:condiments", "en:salad-dressings"],
    ingredientsText: "Soybean oil, water, buttermilk powder, salt, garlic powder, onion powder, vinegar, phosphoric acid, sodium benzoate (to preserve freshness), sorbic acid (to preserve freshness), xanthan gum, artificial flavour, artificial colour (Yellow 5, Yellow 6)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 330,
      carbohydrates_100g: 3,
      sugars_100g: 2,
      proteins_100g: 1,
      salt_100g: 1.8,
      "saturated-fat_100g": 4,
    },
  },
  // ── Cheese calibration (confirmed 2026-06 vs Yuka) ─────────────────────────
  {
    barcode: "0068200885513",
    name: "Old Cheddar",
    brand: "Black Diamond",
    servingSize: "30g",
    categoriesTags: ["en:cheeses", "en:dairy", "en:natural-cheeses"],
    ingredientsText: "Milk, bacterial culture, salt, calcium chloride, microbial enzyme, annatto",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 400,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 25,
      salt_100g: 1.8,
      "saturated-fat_100g": 20,
    },
  },
  {
    barcode: "0062482103525",
    name: "Marble Goat Cheddar",
    brand: "Woolwich",
    servingSize: "30g",
    categoriesTags: ["en:cheeses", "en:dairy", "en:goat-cheeses"],
    ingredientsText: "Pasteurized goat milk, bacterial culture, salt, calcium chloride, microbial enzyme, annatto",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 390,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 22,
      salt_100g: 1.7,
      "saturated-fat_100g": 20,
    },
  },
];

// ── Gorilla Approved whole foods (Canadian brands + international staples) ────

const APPROVED_FOODS: CuratedFoodEntry[] = [
  {
    barcode: "0628451026059",
    name: "Nomz Energy Bites",
    brand: "Nomz",
    servingSize: "30g",
    categoriesTags: ["en:snacks", "en:energy-bars", "en:snack-bars"],
    ingredientsText: "Dates, almonds, cashews, coconut, cacao",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 470,
      carbohydrates_100g: 55,
      sugars_100g: 44,
      proteins_100g: 8,
      "saturated-fat_100g": 6,
      salt_100g: 0.03,
    },
  },
  {
    barcode: "0058755001231",
    name: "Liberté Greek Yogurt Plain 0%",
    brand: "Liberté",
    servingSize: "175g",
    categoriesTags: ["en:dairy", "en:fermented-foods", "en:yogurts", "en:greek-yogurts"],
    ingredientsText: "Skim milk, live active cultures (Lactobacillus bulgaricus, Streptococcus thermophilus)",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 51,
      carbohydrates_100g: 3.9,
      sugars_100g: 3.9,
      proteins_100g: 8.6,
      "saturated-fat_100g": 0,
      salt_100g: 0.1,
    },
  },
  {
    barcode: "0067040303010",
    name: "Hardbite Chips Sea Salt",
    brand: "Hardbite",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks"],
    ingredientsText: "Potatoes, sunflower oil, sea salt",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 58,
      sugars_100g: 0.5,
      proteins_100g: 7,
      "saturated-fat_100g": 1.5,
      salt_100g: 1.2,
    },
  },
  {
    barcode: "0041660300047",
    name: "SkinnyPop Original Popcorn",
    brand: "SkinnyPop",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:popcorn", "en:salty-snacks"],
    ingredientsText: "Popcorn, sunflower oil, salt",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 64,
      sugars_100g: 0,
      proteins_100g: 11,
      "saturated-fat_100g": 3.5,
      salt_100g: 0.9,
    },
  },
  {
    barcode: "0858547004149",
    name: "RXBAR Chocolate Sea Salt",
    brand: "RXBAR",
    servingSize: "52g",
    categoriesTags: ["en:snacks", "en:energy-bars", "en:snack-bars", "en:protein-bars"],
    ingredientsText: "Dates, egg whites, almonds, cashews, cocoa, sea salt, natural chocolate flavour",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 404,
      carbohydrates_100g: 46,
      sugars_100g: 25,
      proteins_100g: 23,
      "saturated-fat_100g": 3.8,
      salt_100g: 0.5,
    },
  },
  {
    barcode: "0021908516890",
    name: "Larabar Apple Pie",
    brand: "Larabar",
    servingSize: "45g",
    categoriesTags: ["en:snacks", "en:energy-bars", "en:snack-bars"],
    ingredientsText: "Dates, almonds, unsweetened apples, walnuts, cinnamon",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 422,
      carbohydrates_100g: 71,
      sugars_100g: 47,
      proteins_100g: 6.7,
      "saturated-fat_100g": 1.1,
      salt_100g: 0,
    },
  },
  {
    // Alternate verified UPC for Wasa (also 0041420064203 above)
    barcode: "0072030007972",
    name: "Wasa Crispbread Whole Grain",
    brand: "Wasa",
    servingSize: "14g",
    categoriesTags: ["en:crackers", "en:crispbreads", "en:snacks"],
    ingredientsText: "Whole grain rye flour, water, salt, yeast",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 350,
      carbohydrates_100g: 64,
      sugars_100g: 1.5,
      proteins_100g: 10,
      salt_100g: 1.2,
      "saturated-fat_100g": 0.3,
      fiber_100g: 18,
    },
  },
  {
    // Alternate verified UPC for SkinnyPop (also 0041660300047 above)
    barcode: "0817939020025",
    name: "SkinnyPop Original Popcorn",
    brand: "SkinnyPop",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:popcorn", "en:salty-snacks"],
    ingredientsText: "Popcorn, sunflower oil, salt",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 64,
      sugars_100g: 0,
      proteins_100g: 11,
      "saturated-fat_100g": 3.5,
      salt_100g: 0.9,
    },
  },
  {
    barcode: "0602652179864",
    name: "KIND Dark Chocolate Nuts & Sea Salt",
    brand: "KIND",
    servingSize: "40g",
    categoriesTags: ["en:snacks", "en:snack-bars", "en:nut-bars"],
    ingredientsText: "Almonds, peanuts, chicory root fiber, honey, palm kernel oil, sugar, cocoa powder, glucose syrup, sea salt, soy lecithin, vanilla extract",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 40,
      sugars_100g: 12.5,
      proteins_100g: 15,
      "saturated-fat_100g": 8.8,
      salt_100g: 0.35,
      fiber_100g: 17.5,
    },
  },
  {
    barcode: "0041570050000",
    name: "Blue Diamond Whole Natural Almonds",
    brand: "Blue Diamond",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:nuts", "en:almonds"],
    ingredientsText: "Almonds",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 607,
      carbohydrates_100g: 21,
      sugars_100g: 4.4,
      proteins_100g: 21.4,
      "saturated-fat_100g": 3.6,
      salt_100g: 0,
      fiber_100g: 12.5,
    },
  },
  {
    barcode: "0856205006050",
    name: "CHOMPS Original Beef Jerky Stick",
    brand: "CHOMPS",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:meat-snacks", "en:jerky"],
    ingredientsText: "Grass-fed beef, water, encapsulated citric acid, sea salt, celery juice powder",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 321,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 32,
      "saturated-fat_100g": 7,
      salt_100g: 3.1,
    },
  },
  {
    barcode: "0856205006067",
    name: "CHOMPS Free Range Turkey Jerky Stick",
    brand: "CHOMPS",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:meat-snacks", "en:jerky"],
    ingredientsText: "Free range turkey, water, celery juice powder, sea salt",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 250,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 32,
      "saturated-fat_100g": 3.5,
      salt_100g: 2.8,
    },
  },
  {
    barcode: "0026617014109",
    name: "Wonderful Pistachios No Shell",
    brand: "Wonderful Pistachios",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:nuts", "en:pistachios"],
    ingredientsText: "Pistachios, salt",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 571,
      carbohydrates_100g: 27,
      sugars_100g: 8,
      proteins_100g: 20,
      "saturated-fat_100g": 5.5,
      salt_100g: 0.9,
      fiber_100g: 10.5,
    },
  },
  {
    barcode: "0851093001029",
    name: "GimMe Organic Roasted Seaweed Snacks",
    brand: "GimMe",
    servingSize: "5g",
    categoriesTags: ["en:snacks", "en:seaweed-snacks", "en:plant-based"],
    ingredientsText: "Organic seaweed, organic expeller pressed sunflower oil, sea salt",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 20,
      sugars_100g: 0,
      proteins_100g: 20,
      "saturated-fat_100g": 10,
      salt_100g: 5.8,
    },
  },
  {
    barcode: "0851093001036",
    name: "GimMe Organic Roasted Seaweed Snacks",
    brand: "GimMe",
    servingSize: "10g",
    categoriesTags: ["en:snacks", "en:seaweed-snacks", "en:plant-based"],
    ingredientsText: "Organic seaweed, organic expeller pressed sunflower oil, sea salt",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 20,
      sugars_100g: 0,
      proteins_100g: 20,
      "saturated-fat_100g": 10,
      salt_100g: 5.8,
    },
  },
  {
    barcode: "0058755000999",
    name: "Liberté Greek Yogurt Plain 0%",
    brand: "Liberté",
    servingSize: "175g",
    categoriesTags: ["en:dairy", "en:fermented-foods", "en:yogurts", "en:greek-yogurts"],
    ingredientsText: "Skim milk, live active cultures (Lactobacillus bulgaricus, Streptococcus thermophilus)",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 51,
      carbohydrates_100g: 3.9,
      sugars_100g: 3.9,
      proteins_100g: 8.6,
      "saturated-fat_100g": 0,
      salt_100g: 0.1,
    },
  },
];

// ── Cheat list Canadian products ──────────────────────────────────────────────

const CHEAT_LIST_FOODS: CuratedFoodEntry[] = [
  {
    barcode: "0060410016476",
    name: "Miss Vickie's Sea Salt & Malt Vinegar",
    brand: "Miss Vickie's",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:kettle-chips", "en:salty-snacks"],
    ingredientsText: "Potatoes, sunflower oil, seasoning (malt vinegar powder, sea salt, maltodextrin, yeast extract)",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 62,
      sugars_100g: 1.5,
      proteins_100g: 7,
      "saturated-fat_100g": 1.8,
      salt_100g: 1.4,
    },
  },
  {
    barcode: "0063600013113",
    name: "Breton Original Crackers",
    brand: "Dare Foods",
    servingSize: "30g",
    categoriesTags: ["en:snacks", "en:crackers", "en:biscuits-and-cakes"],
    ingredientsText: "Wheat flour, vegetable oil (palm, canola), whole wheat flour, sugar, salt, leavening agents, soy lecithin",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 444,
      carbohydrates_100g: 65,
      sugars_100g: 5,
      proteins_100g: 8,
      "saturated-fat_100g": 4,
      salt_100g: 1.6,
    },
  },
  {
    barcode: "0607813037016",
    name: "Boom Chicka Pop White Cheddar Popcorn",
    brand: "Angie's Boomchickapop",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:popcorn", "en:salty-snacks"],
    ingredientsText: "Popcorn, sunflower oil, white cheddar seasoning (whey, cheddar cheese, salt, natural flavours, lactic acid)",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 57,
      sugars_100g: 3.6,
      proteins_100g: 10.7,
      "saturated-fat_100g": 6,
      salt_100g: 1.4,
    },
  },
  {
    barcode: "0062814133450",
    name: "Lindt Excellence 85% Dark Chocolate",
    brand: "Lindt",
    servingSize: "40g",
    categoriesTags: ["en:snacks", "en:chocolate", "en:dark-chocolate", "en:candies"],
    ingredientsText: "Chocolate mass, fat-reduced cocoa powder, cocoa butter, sugar, bourbon vanilla beans",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 648,
      carbohydrates_100g: 22,
      sugars_100g: 3.5,
      proteins_100g: 11,
      "saturated-fat_100g": 32,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0037466012834",
    name: "Lindt Excellence 85% Dark Chocolate",
    brand: "Lindt",
    servingSize: "40g",
    categoriesTags: ["en:snacks", "en:chocolate", "en:dark-chocolate", "en:candies"],
    ingredientsText: "Chocolate mass, fat-reduced cocoa powder, cocoa butter, sugar, bourbon vanilla beans",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 648,
      carbohydrates_100g: 22,
      sugars_100g: 3.5,
      proteins_100g: 11,
      "saturated-fat_100g": 32,
      salt_100g: 0.01,
    },
  },
  {
    barcode: "0062814133443",
    name: "Lindt Excellence 70% Dark Chocolate",
    brand: "Lindt",
    servingSize: "40g",
    categoriesTags: ["en:snacks", "en:chocolate", "en:dark-chocolate", "en:candies"],
    ingredientsText: "Chocolate mass, sugar, fat-reduced cocoa powder, cocoa butter, emulsifier (soy lecithin), bourbon vanilla beans",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 590,
      carbohydrates_100g: 42,
      sugars_100g: 29,
      proteins_100g: 8,
      "saturated-fat_100g": 25,
      salt_100g: 0.03,
    },
  },
  {
    barcode: "0708656035003",
    name: "Green & Black's Organic 70% Dark Chocolate",
    brand: "Green & Black's",
    servingSize: "40g",
    categoriesTags: ["en:snacks", "en:chocolate", "en:dark-chocolate", "en:candies", "en:organic"],
    ingredientsText: "Organic chocolate (organic chocolate liquor, organic sugar, organic cocoa butter, vanilla extract), organic cocoa butter",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 560,
      carbohydrates_100g: 42,
      sugars_100g: 33,
      proteins_100g: 9,
      "saturated-fat_100g": 26,
      salt_100g: 0.03,
    },
  },
  {
    barcode: "0016000275287",
    name: "Nature Valley Crunchy Oats 'n Honey Granola Bars",
    brand: "Nature Valley",
    servingSize: "42g",
    categoriesTags: ["en:snacks", "en:granola-bars", "en:snack-bars", "en:cereal-bars"],
    ingredientsText: "Whole grain oats, sugar, modified palm and palm kernel oil, yellow corn flour, honey, soy flour, salt, baking soda",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 471,
      carbohydrates_100g: 65,
      sugars_100g: 24,
      proteins_100g: 9,
      "saturated-fat_100g": 5.5,
      salt_100g: 0.7,
      fiber_100g: 5,
    },
  },
  {
    barcode: "0016000275225",
    name: "Nature Valley Crunchy Oats 'n Honey Granola Bars",
    brand: "Nature Valley",
    servingSize: "42g",
    categoriesTags: ["en:snacks", "en:granola-bars", "en:snack-bars", "en:cereal-bars"],
    ingredientsText: "Whole grain oats, sugar, modified palm and palm kernel oil, yellow corn flour, honey, soy flour, salt, baking soda",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 471,
      carbohydrates_100g: 65,
      sugars_100g: 24,
      proteins_100g: 9,
      "saturated-fat_100g": 5.5,
      salt_100g: 0.7,
      fiber_100g: 5,
    },
  },
  {
    barcode: "0044000051396",
    name: "Triscuit Original Crackers",
    brand: "Nabisco",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:crackers", "en:whole-grain-crackers"],
    ingredientsText: "Whole grain soft winter wheat, canola oil, sea salt",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 400,
      carbohydrates_100g: 62,
      sugars_100g: 0,
      proteins_100g: 10,
      "saturated-fat_100g": 1,
      salt_100g: 1.3,
      fiber_100g: 8.6,
    },
  },
  {
    barcode: "0044000032036",
    name: "Triscuit Original Crackers",
    brand: "Nabisco",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:crackers", "en:whole-grain-crackers"],
    ingredientsText: "Whole grain soft winter wheat, canola oil, sea salt",
    novaGroup: 2,
    nutriments: {
      "energy-kcal_100g": 400,
      carbohydrates_100g: 62,
      sugars_100g: 0,
      proteins_100g: 10,
      "saturated-fat_100g": 1,
      salt_100g: 1.3,
      fiber_100g: 8.6,
    },
  },
  {
    barcode: "0028400493451",
    name: "Smartfood White Cheddar Popcorn",
    brand: "Smartfood",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:popcorn", "en:cheese-popcorn", "en:salty-snacks"],
    ingredientsText: "Popcorn, cheddar cheese (milk, cheese cultures, salt, enzymes), sunflower oil, whey, buttermilk, salt, natural flavour",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 60,
      sugars_100g: 3,
      proteins_100g: 10,
      "saturated-fat_100g": 7,
      salt_100g: 1.3,
    },
  },
];

// ── Stay Away Canadian products ───────────────────────────────────────────────

const STAY_AWAY_FOODS: CuratedFoodEntry[] = [
  {
    barcode: "0060383060019",
    name: "Old Dutch Party Mix",
    brand: "Old Dutch Foods",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:salty-snacks", "en:snack-mixes"],
    ingredientsText: "Corn meal, vegetable oil, potato starch, salt, sugar, seasonings, artificial colour, TBHQ",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 480,
      carbohydrates_100g: 65,
      sugars_100g: 3,
      proteins_100g: 7,
      "saturated-fat_100g": 5,
      salt_100g: 1.5,
    },
  },
  {
    barcode: "0060383070025",
    name: "Humpty Dumpty Cheese Sticks",
    brand: "Old Dutch Foods",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:salty-snacks", "en:chips-and-crisps"],
    ingredientsText: "Cornmeal, vegetable oil, cheddar cheese seasoning (whey powder, cheddar cheese, maltodextrin, salt, natural cheese flavour, Yellow 5, Yellow 6)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 60,
      sugars_100g: 2,
      proteins_100g: 7,
      "saturated-fat_100g": 8,
      salt_100g: 1.5,
    },
  },
  {
    barcode: "0060383089027",
    name: "Arriba Nacho Chips",
    brand: "Old Dutch Foods",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks", "en:tortilla-chips"],
    ingredientsText: "Corn masa flour, vegetable oil, salt, seasoning (maltodextrin, monosodium glutamate, artificial colour)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 500,
      carbohydrates_100g: 62,
      sugars_100g: 1,
      proteins_100g: 7,
      "saturated-fat_100g": 4,
      salt_100g: 1.4,
    },
  },
  {
    barcode: "0028400090209",
    name: "Cheetos Crunchy",
    brand: "Frito-Lay",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks", "en:cheese-puffs"],
    ingredientsText: "Corn meal, vegetable oil (corn, canola, or sunflower oil), cheese seasoning (whey, cheddar cheese, maltodextrin, salt, monosodium glutamate, lactic acid, citric acid, artificial color Yellow 6)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 59,
      sugars_100g: 3.5,
      proteins_100g: 7.5,
      "saturated-fat_100g": 5,
      salt_100g: 1.6,
    },
  },
  {
    barcode: "0028400422161",
    name: "Cheetos Crunchy",
    brand: "Frito-Lay",
    servingSize: "28g",
    categoriesTags: ["en:snacks", "en:chips-and-crisps", "en:salty-snacks", "en:cheese-puffs"],
    ingredientsText: "Corn meal, vegetable oil (corn, canola, or sunflower oil), cheese seasoning (whey, cheddar cheese, maltodextrin, salt, monosodium glutamate, lactic acid, citric acid, artificial color Yellow 6)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 536,
      carbohydrates_100g: 59,
      sugars_100g: 3.5,
      proteins_100g: 7.5,
      "saturated-fat_100g": 5,
      salt_100g: 1.6,
    },
  },
  {
    barcode: "0038000219351",
    name: "Pop-Tarts Frosted Brown Sugar Cinnamon",
    brand: "Kellogg's",
    servingSize: "52g",
    categoriesTags: ["en:snacks", "en:sweet-snacks", "en:toaster-pastries", "en:biscuits-and-cakes"],
    ingredientsText: "Enriched flour (wheat flour, niacin, reduced iron, thiamin mononitrate, riboflavin, folic acid), high fructose corn syrup, soybean oil, dextrose, corn syrup, sugar, cracker meal, cinnamon, artificial and natural flavors, salt, leavening, gelatin, caramel color, Yellow 5, Yellow 6, Red 40",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 382,
      carbohydrates_100g: 71,
      sugars_100g: 32,
      proteins_100g: 5,
      "saturated-fat_100g": 2.5,
      salt_100g: 0.6,
    },
  },
  {
    barcode: "0044700038048",
    name: "Lunchables Turkey & Cheddar Cracker Stacker",
    brand: "Oscar Mayer",
    servingSize: "90g",
    categoriesTags: ["en:snacks", "en:ready-meals", "en:processed-meats"],
    ingredientsText: "Turkey (turkey, water, salt, sodium phosphates, dextrose), crackers (enriched flour, soybean oil, sugar, salt, leavening), cheddar cheese (milk, cheese cultures, salt, enzymes, annatto extract), protein candy",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 280,
      carbohydrates_100g: 28,
      sugars_100g: 6,
      proteins_100g: 12,
      "saturated-fat_100g": 5,
      salt_100g: 1.7,
    },
  },
  {
    barcode: "0009800895023",
    name: "Nutella Hazelnut Spread",
    brand: "Ferrero",
    servingSize: "37g",
    categoriesTags: ["en:spreads", "en:sweet-spreads", "en:nut-based-spreads", "en:chocolate-spreads"],
    ingredientsText: "Sugar, palm oil, hazelnuts (13%), skim milk powder, fat-reduced cocoa powder, soy lecithin as emulsifier, vanillin (artificial flavor)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 541,
      carbohydrates_100g: 58,
      sugars_100g: 56,
      proteins_100g: 6.3,
      "saturated-fat_100g": 10.6,
      salt_100g: 0.1,
    },
  },
  {
    barcode: "0055577102202",
    name: "Harvest Crunch Original Granola",
    brand: "Quaker",
    servingSize: "45g",
    categoriesTags: ["en:cereals-and-their-products", "en:granolas", "en:breakfast-cereals"],
    ingredientsText: "Rolled oats, sugar, coconut and/or soybean oil, honey, toasted almonds, sesame seeds, salt, baking soda",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 471,
      carbohydrates_100g: 65,
      sugars_100g: 27,
      proteins_100g: 9,
      "saturated-fat_100g": 9,
      salt_100g: 0.7,
      fiber_100g: 4.5,
    },
  },
  {
    barcode: "0722252102729",
    name: "CLIF Bar Chocolate Chip",
    brand: "CLIF Bar",
    servingSize: "68g",
    categoriesTags: ["en:snacks", "en:energy-bars", "en:snack-bars", "en:protein-bars"],
    ingredientsText: "Organic brown rice syrup, organic rolled oats, soy protein isolate, organic dried cane syrup, organic oat fiber, maltodextrin, organic soy flour, chocolate chips (sugar, chocolate liquor, cocoa butter, soy lecithin, vanillin), beet sugar, soy lecithin, natural flavors",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 375,
      carbohydrates_100g: 64,
      sugars_100g: 35,
      proteins_100g: 10,
      "saturated-fat_100g": 2,
      salt_100g: 0.5,
      fiber_100g: 5,
    },
  },
  {
    barcode: "0722252010672",
    name: "CLIF Bar Oatmeal Raisin Walnut",
    brand: "CLIF Bar",
    servingSize: "68g",
    categoriesTags: ["en:snacks", "en:energy-bars", "en:snack-bars", "en:protein-bars"],
    ingredientsText: "Organic brown rice syrup, organic rolled oats, soy protein isolate, organic dried cane syrup, organic oat fiber, maltodextrin, organic soy flour, walnuts, raisins, beet sugar, soy lecithin, natural flavors",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 375,
      carbohydrates_100g: 64,
      sugars_100g: 35,
      proteins_100g: 10,
      "saturated-fat_100g": 2,
      salt_100g: 0.5,
      fiber_100g: 5,
    },
  },
  {
    barcode: "0038000014833",
    name: "Activia Strawberry Probiotic Yogurt",
    brand: "Danone",
    servingSize: "125g",
    categoriesTags: ["en:dairy", "en:yogurts", "en:fermented-foods", "en:flavored-yogurts"],
    ingredientsText: "Skim milk, strawberries, sugar, modified corn starch, carmine (natural color), natural flavor, live and active cultures (Streptococcus thermophilus, Lactobacillus bulgaricus, Bifidobacterium animalis lactis)",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 80,
      carbohydrates_100g: 13,
      sugars_100g: 11,
      proteins_100g: 3.5,
      "saturated-fat_100g": 1,
      salt_100g: 0.07,
    },
  },
  {
    barcode: "0038000012557",
    name: "Special K Protein Bar Chocolate Peanut Butter",
    brand: "Kellogg's",
    servingSize: "45g",
    categoriesTags: ["en:snacks", "en:snack-bars", "en:protein-bars", "en:cereal-bars"],
    ingredientsText: "Soy protein nuggets (soy protein isolate, tapioca starch, salt), chocolate flavored coating (sugar, palm kernel oil, cocoa powder, skim milk, soy lecithin, salt, vanillin), glucose syrup, sugar, oats, palm kernel oil, brown rice flour, glycerol, natural flavors",
    novaGroup: 4,
    nutriments: {
      "energy-kcal_100g": 380,
      carbohydrates_100g: 60,
      sugars_100g: 33,
      proteins_100g: 15,
      "saturated-fat_100g": 6,
      salt_100g: 0.5,
    },
  },
];

// ── Curated supplement fallback (guaranteed hits for top-selling supplements) ──
// Nutrition values per 100g of product (not per serving).

const SUPPLEMENTS: CuratedFoodEntry[] = [
  {
    barcode: "748927059380",
    name: "Gold Standard Creatine Monohydrate",
    brand: "Optimum Nutrition",
    servingSize: "5g",
    categoriesTags: ["en:dietary-supplements", "en:sports-nutrition", "en:creatine"],
    ingredientsText: "Creatine Monohydrate, Silicon Dioxide",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0,
    },
  },
  {
    barcode: "768990027710",
    name: "Ultimate Omega Fish Oil",
    brand: "Nordic Naturals",
    servingSize: "2 softgels (2.6g)",
    categoriesTags: ["en:dietary-supplements", "en:omega-3", "en:fish-oil"],
    ingredientsText: "Fish oil concentrate (anchovy, sardine), gelatin, glycerin, water, natural lemon flavour",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 962,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      "saturated-fat_100g": 19.2,
      salt_100g: 0,
    },
  },
  {
    barcode: "689076626498",
    name: "Whey+ Protein Powder",
    brand: "Legion Athletics",
    servingSize: "35g",
    categoriesTags: ["en:dietary-supplements", "en:sports-nutrition", "en:protein-powders", "en:whey-protein"],
    ingredientsText: "Whey protein isolate, whey protein concentrate, natural flavours, sunflower lecithin, stevia leaf extract",
    novaGroup: 3,
    nutriments: {
      "energy-kcal_100g": 371,
      carbohydrates_100g: 11.4,
      sugars_100g: 5.7,
      proteins_100g: 62.9,
      "saturated-fat_100g": 2.9,
      salt_100g: 0.4,
    },
  },
  {
    barcode: "850002454025",
    name: "Creatine HMB",
    brand: "Transparent Labs",
    servingSize: "14.5g",
    categoriesTags: ["en:dietary-supplements", "en:sports-nutrition", "en:creatine"],
    ingredientsText: "Creatine monohydrate, calcium beta-hydroxy beta-methylbutyrate (HMB), malic acid, silicon dioxide, stevia leaf extract",
    novaGroup: 1,
    nutriments: {
      "energy-kcal_100g": 0,
      carbohydrates_100g: 0,
      sugars_100g: 0,
      proteins_100g: 0,
      salt_100g: 0,
    },
  },
];

const ALL_ENTRIES: CuratedFoodEntry[] = [...SODAS, ...PACKAGED_FOODS, ...APPROVED_FOODS, ...CHEAT_LIST_FOODS, ...STAY_AWAY_FOODS, ...SUPPLEMENTS];

// Normalise a barcode string: strip non-digits, strip leading zeros.
function normBarcode(b: string): string {
  return b.replace(/\D/g, "").replace(/^0+/, "") || "0";
}

/** Search curated foods (non-supplement) by name or brand (case-insensitive). */
export function searchCuratedFoods(query: string, limit = 5): CuratedFoodEntry[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  const nonSuppl = ALL_ENTRIES.filter((e) => !e.categoriesTags.includes("en:dietary-supplements"));
  return nonSuppl.filter(
    (e) => e.name.toLowerCase().includes(q) || e.brand.toLowerCase().includes(q)
  ).slice(0, limit);
}

/** Search curated supplements by name or brand (case-insensitive). */
export function searchCuratedSupplements(query: string, limit = 4): CuratedFoodEntry[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return SUPPLEMENTS.filter(
    (e) => e.name.toLowerCase().includes(q) || e.brand.toLowerCase().includes(q)
  ).slice(0, limit);
}

/**
 * Look up a barcode in the curated food database.
 * Returns an OffProduct ready for the normal food scoring pipeline, or null.
 */
export function lookupCuratedFood(barcode: string): OffProduct | null {
  const norm = normBarcode(barcode);
  const entry = ALL_ENTRIES.find((e) => normBarcode(e.barcode) === norm);
  if (!entry) return null;

  return {
    code: barcode,
    product_name: entry.name,
    brands: entry.brand,
    serving_size: entry.servingSize,
    categories_tags: entry.categoriesTags,
    ingredients_text: entry.ingredientsText,
    nutriments: entry.nutriments,
    nova_group: entry.novaGroup,
  };
}
